import React, { useEffect, useState } from 'react';
import { CheckCircle2, Eye, ShieldCheck, XCircle } from 'lucide-react';
import { isStep94VerifiedSqsDraft } from './authorCandidateReadiness.js';

export function AuthorCandidateReadinessPreview({ draft, authorEmail, storageMode, planningValidation, contentValidation, reviewValidation, onPreview, onReadinessChange, setMessage }) {
  const [preview, setPreview] = useState(null);
  const [working, setWorking] = useState(false);
  const applies = storageMode === 'shared_supabase' && isStep94VerifiedSqsDraft(draft);

  useEffect(() => {
    setPreview(null);
    onReadinessChange?.(false);
  }, [draft?.draft?.revision, draft?.draft?.updatedAt, onReadinessChange]);

  if (!applies) return null;

  const runPreview = async () => {
    setWorking(true);
    setMessage('Checking the saved SQS Shared Draft without creating a candidate...');
    const result = await onPreview?.({ draft, authorEmail, planningValidation, contentValidation, reviewValidation });
    setWorking(false);
    if (!result?.success) {
      setPreview(null);
      onReadinessChange?.(false);
      setMessage(result?.error || 'The read-only candidate-readiness preview could not be completed.');
      return;
    }
    setPreview(result);
    onReadinessChange?.(result.readyForCandidateGeneration);
    setMessage(result.readyForCandidateGeneration
      ? 'Read-only Stage 12 preview passed. No candidate key was generated.'
      : result.currentRevisionCandidateCount > 0 && result.existingCandidateRecords.every(item => item.valid)
        ? 'An immutable candidate already exists for this revision. It was verified and no new key was generated.'
        : 'The read-only Stage 12 preview found a blocking difference. No candidate key was generated.');
  };

  return <section aria-label="Read-only Stage 12 candidate readiness" className="rounded-2xl border border-violet-800 bg-violet-950/20 p-5 space-y-4">
    <div className="flex items-start gap-3"><Eye className="w-6 h-6 text-violet-300 shrink-0" /><div><span className="text-xs font-bold uppercase tracking-wider text-violet-300">Step 94 · Read-only preview</span><h3 className="text-lg font-bold text-white mt-1">Check candidate readiness</h3><p className="text-xs text-slate-300 mt-1">This reads the saved SQS draft and existing candidate records. It creates no candidate key and performs no write.</p></div></div>
    <button type="button" disabled={working} onClick={() => void runPreview()} className="px-4 py-2.5 rounded-xl bg-violet-700 disabled:opacity-50 text-xs font-bold text-white inline-flex items-center gap-2"><ShieldCheck className="w-4 h-4" /> {working ? 'Checking Readiness...' : 'Preview Stage 12 Readiness'}</button>
    {preview && <div className="space-y-4">
      <div className={`rounded-xl border p-3 text-xs ${preview.readyForCandidateGeneration ? 'border-emerald-800 bg-emerald-950/20 text-emerald-200' : preview.currentRevisionCandidateCount > 0 ? 'border-cyan-800 bg-cyan-950/20 text-cyan-200' : 'border-rose-800 bg-rose-950/20 text-rose-200'}`}><strong>{preview.readyForCandidateGeneration ? 'READY FOR YOUR LATER MANUAL CANDIDATE STEP' : preview.currentRevisionCandidateCount > 0 ? 'IMMUTABLE CANDIDATE ALREADY EXISTS — DO NOT GENERATE ANOTHER' : 'NOT READY FOR CANDIDATE GENERATION'}</strong><span className="block mt-1">Candidate IDs generated by this preview: 0 · Database writes: 0</span></div>
      <div className="grid grid-cols-1 sm:grid-cols-4 gap-3 text-xs"><div><span className="block text-slate-500">Signed-in Author</span><strong className="text-white break-all">{preview.intendedAuthor.email || preview.intendedAuthor.id}</strong></div><div><span className="block text-slate-500">Shared revision</span><strong className="text-white">{preview.currentRevision}</strong></div><div><span className="block text-slate-500">Candidate records for this draft</span><strong className={preview.draftCandidateCount === 0 ? 'text-emerald-300' : 'text-amber-300'}>{preview.draftCandidateCount}</strong></div><div><span className="block text-slate-500">Duplicate candidate state</span><strong className={preview.currentRevisionCandidateCount === 0 ? 'text-emerald-300' : 'text-rose-300'}>{preview.currentRevisionCandidateCount === 0 ? 'None for this revision' : `${preview.currentRevisionCandidateCount} already exists`}</strong></div></div>
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-2 text-[10px] text-slate-300"><span>{preview.counts.phaseCount} phases</span><span>{preview.counts.taskCount} tasks</span><span>{preview.counts.checkboxCount} checkboxes</span><span>{preview.counts.verificationCheckCount} checks</span><span>{preview.counts.cleanupItemCount} cleanup items</span><span>{preview.counts.learnerResourceValueCount} resource values</span><span>{preview.counts.officialAwsSourceCount} AWS sources</span></div>
      <div className="rounded-xl border border-slate-800 bg-slate-950/50 p-3 space-y-2 text-[10px] text-slate-400"><span className="block">Draft ID: <code className="text-slate-200 break-all">{preview.draftId}</code></span><span className="block">Server owner ID: <code className="text-slate-200 break-all">{preview.serverOwnerId}</code></span><span className="block">Handoff SHA-256: <code className="text-emerald-300 break-all">{preview.fingerprints.handoff}</code></span><span className="block">Accepted-content SHA-256: <code className="text-cyan-300 break-all">{preview.fingerprints.acceptedContent}</code></span><span className="block">Open draft SHA-256: <code className="text-cyan-300 break-all">{preview.fingerprints.currentDraft}</code></span><span className="block">Saved Shared Draft SHA-256: <code className="text-cyan-300 break-all">{preview.fingerprints.savedSharedDraft}</code></span><span className="block">Database content SHA-256: <code className="text-violet-300 break-all">{preview.fingerprints.databaseContent}</code></span></div>
      {preview.existingCandidateRecords.map(item => <section key={item.candidateId} className="rounded-xl border border-cyan-800 bg-cyan-950/20 p-4 space-y-3"><div><strong className="text-sm text-white">Existing Shared Candidate Approval Key</strong><code className="block mt-2 rounded-lg border border-cyan-900 bg-slate-950 p-3 text-xs text-cyan-100 break-all select-all">{item.candidateId}</code></div><div className="grid grid-cols-1 sm:grid-cols-3 gap-2 text-xs"><span><span className="block text-slate-500">Source revision</span><strong className="text-white">{item.sourceRevision}</strong></span><span><span className="block text-slate-500">Status</span><strong className="text-amber-300">{item.status}</strong></span><span><span className="block text-slate-500">Approval</span><strong className="text-white">{item.approvalDecision}</strong></span></div><span className="block text-[10px] text-slate-400">Candidate key snapshot SHA-256: <code className="text-cyan-200 break-all">{item.clientSnapshotHash}</code></span><span className="block text-[10px] text-slate-400">Protected server snapshot SHA-256: <code className="text-violet-200 break-all">{item.contentHash}</code></span><div className={`rounded-lg border p-3 text-xs ${item.valid ? 'border-emerald-800 bg-emerald-950/20 text-emerald-200' : 'border-rose-800 bg-rose-950/20 text-rose-200'}`}>{item.valid ? 'Candidate key, snapshot, owner, source revision and saved draft hash all match.' : 'Candidate verification failed. Do not send this key for approval.'}</div></section>)}
      <ol className="space-y-2">{preview.checks.map((item, index) => <li key={item.id} className={`rounded-xl border p-3 text-xs flex items-start gap-2 ${item.passed ? 'border-emerald-900 bg-emerald-950/10 text-emerald-200' : 'border-rose-900 bg-rose-950/20 text-rose-200'}`}>{item.passed ? <CheckCircle2 className="w-4 h-4 shrink-0" /> : <XCircle className="w-4 h-4 shrink-0" />}<span><strong>{index + 1}. {item.label}</strong><span className="block mt-1 text-slate-400">{item.detail}</span></span></li>)}</ol>
    </div>}
  </section>;
}
