-- Publish the 100 locally reviewed Terraform Associate (004) questions.
-- Scope: Terraform questions q-tf004-1 through q-tf004-100 and their topic links only.
-- AWS questions, exam attempts, Follow Alongs, drafts and approvals are not changed.

BEGIN;

CREATE TEMP TABLE terraform_004_question_seed (
  id TEXT PRIMARY KEY,
  exam_code TEXT NOT NULL,
  difficulty TEXT,
  question_type TEXT NOT NULL,
  question_text TEXT NOT NULL,
  option_a TEXT NOT NULL,
  option_b TEXT NOT NULL,
  option_c TEXT NOT NULL,
  option_d TEXT NOT NULL,
  option_e TEXT,
  option_f TEXT,
  correct_answer INTEGER NOT NULL,
  correct_answers INTEGER[] NOT NULL,
  explanation TEXT,
  topic_id TEXT NOT NULL
) ON COMMIT DROP;

INSERT INTO terraform_004_question_seed (
  id, exam_code, difficulty, question_type, question_text,
  option_a, option_b, option_c, option_d, option_e, option_f,
  correct_answer, correct_answers, explanation, topic_id
) VALUES
  ($tfq$q-tf004-1$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Easy$tfq$, $tfq$single$tfq$, $tfq$A team currently creates development environments by following a shared checklist. What is the strongest reason to replace that process with Terraform configuration stored in version control?$tfq$, $tfq$It guarantees that cloud providers never change their service APIs$tfq$, $tfq$It makes infrastructure changes repeatable, reviewable, and auditable$tfq$, $tfq$It removes the need to authenticate to infrastructure providers$tfq$, $tfq$It prevents anyone from changing infrastructure outside Terraform$tfq$, NULL, NULL, 1, ARRAY[1]::INTEGER[], $tfq$Version-controlled Terraform configuration gives the team a repeatable definition of the intended infrastructure and a reviewable history of changes. It does not prevent drift, remove authentication, or control provider APIs.$tfq$, $tfq$tf004-iac$tfq$),
  ($tfq$q-tf004-2$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Medium$tfq$, $tfq$single$tfq$, $tfq$One Terraform configuration manages resources in AWS and an external monitoring service. How can Terraform use one workflow for both services?$tfq$, $tfq$It translates both services into the same native cloud template format$tfq$, $tfq$It stores each service object in a separate Terraform executable$tfq$, $tfq$It uses a provider plugin that implements each service API$tfq$, $tfq$It mirrors all service APIs into the Terraform state file$tfq$, NULL, NULL, 2, ARRAY[2]::INTEGER[], $tfq$Providers are plugins that let Terraform communicate with cloud, SaaS, and other service APIs. The workflow stays consistent while each provider implements the operations needed for its own service.$tfq$, $tfq$tf004-iac$tfq$),
  ($tfq$q-tf004-3$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Easy$tfq$, $tfq$single$tfq$, $tfq$A learner has cloned a valid Terraform configuration into a new empty working directory. Which command should they run before creating a plan?$tfq$, $tfq$terraform validate$tfq$, $tfq$terraform providers lock$tfq$, $tfq$terraform init$tfq$, $tfq$terraform refresh$tfq$, NULL, NULL, 2, ARRAY[2]::INTEGER[], $tfq$terraform init prepares the working directory, initializes the configured backend, and installs required providers and modules. Validation and planning normally follow initialization.$tfq$, $tfq$tf004-fundamentals$tfq$),
  ($tfq$q-tf004-4$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Medium$tfq$, $tfq$single$tfq$, $tfq$Why should a team commit the .terraform.lock.hcl dependency lock file to version control?$tfq$, $tfq$It stores the credentials used by every configured provider$tfq$, $tfq$It records selected provider versions and package checksums$tfq$, $tfq$It replaces all provider constraints in required_providers$tfq$, $tfq$It contains the latest remote objects recorded in state$tfq$, NULL, NULL, 1, ARRAY[1]::INTEGER[], $tfq$The dependency lock file records selected provider versions and checksums so later initialization can make consistent provider selections and verify downloaded packages. It does not store credentials or infrastructure state.$tfq$, $tfq$tf004-fundamentals$tfq$),
  ($tfq$q-tf004-5$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Easy$tfq$, $tfq$single$tfq$, $tfq$A change has been written and validated. Which command shows the proposed actions without changing the managed infrastructure?$tfq$, $tfq$terraform apply$tfq$, $tfq$terraform plan$tfq$, $tfq$terraform state show$tfq$, $tfq$terraform output$tfq$, NULL, NULL, 1, ARRAY[1]::INTEGER[], $tfq$terraform plan compares configuration, prior state, and refreshed remote object information to propose an execution plan. It does not apply the proposed infrastructure changes.$tfq$, $tfq$tf004-workflow$tfq$),
  ($tfq$q-tf004-6$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Medium$tfq$, $tfq$single$tfq$, $tfq$A team reviews a plan saved as tfplan. What is the main benefit of running terraform apply tfplan instead of terraform apply with no plan file?$tfq$, $tfq$Terraform applies the exact saved plan that the team reviewed$tfq$, $tfq$Terraform upgrades all providers before applying the changes$tfq$, $tfq$Terraform bypasses provider authentication for that operation$tfq$, $tfq$Terraform disables state refresh and locking for that operation$tfq$, NULL, NULL, 0, ARRAY[0]::INTEGER[], $tfq$Supplying a saved plan tells Terraform to apply that reviewed plan rather than generating a new speculative plan. Provider authentication and normal safety behavior are still required.$tfq$, $tfq$tf004-workflow$tfq$),
  ($tfq$q-tf004-7$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Easy$tfq$, $tfq$single$tfq$, $tfq$A network already exists and Terraform only needs to read its attributes for use by another resource. Which block type is most appropriate?$tfq$, $tfq$A resource block$tfq$, $tfq$A moved block$tfq$, $tfq$A data block$tfq$, $tfq$An output block$tfq$, NULL, NULL, 2, ARRAY[2]::INTEGER[], $tfq$A data block reads information from an existing object without declaring that object as managed by the current configuration. A resource block is used when Terraform should manage the object lifecycle.$tfq$, $tfq$tf004-configuration$tfq$),
  ($tfq$q-tf004-8$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Medium$tfq$, $tfq$single$tfq$, $tfq$When should an author normally add an explicit depends_on relationship?$tfq$, $tfq$Whenever two resources use the same provider configuration$tfq$, $tfq$When a required dependency is not visible in value references$tfq$, $tfq$Whenever a resource has more than one configuration argument$tfq$, $tfq$When a variable value is supplied from a tfvars file$tfq$, NULL, NULL, 1, ARRAY[1]::INTEGER[], $tfq$Terraform infers dependencies from references in expressions. depends_on is appropriate for a real behavioral dependency that Terraform cannot infer from those references.$tfq$, $tfq$tf004-configuration$tfq$),
  ($tfq$q-tf004-9$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Easy$tfq$, $tfq$single$tfq$, $tfq$How does a root module normally pass an environment name into a child module?$tfq$, $tfq$By assigning a value to a declared child-module input$tfq$, $tfq$By writing the value directly into the child state file$tfq$, $tfq$By adding the value to the provider dependency lock file$tfq$, $tfq$By exporting the value from a saved execution plan$tfq$, NULL, NULL, 0, ARRAY[0]::INTEGER[], $tfq$The child module declares an input variable and the calling module assigns its value in the module block. Module inputs form the supported interface between the caller and child.$tfq$, $tfq$tf004-modules$tfq$),
  ($tfq$q-tf004-10$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Medium$tfq$, $tfq$single$tfq$, $tfq$A team wants a publicly discoverable module with published versions and documentation. Which source is designed for this use?$tfq$, $tfq$A local Terraform state file$tfq$, $tfq$A saved Terraform plan file$tfq$, $tfq$The Terraform dependency lock file$tfq$, $tfq$The public Terraform Registry$tfq$, NULL, NULL, 3, ARRAY[3]::INTEGER[], $tfq$The public Terraform Registry provides discoverable and versioned modules with documentation. Local state, plan files, and provider lock files are not module distribution services.$tfq$, $tfq$tf004-modules$tfq$),
  ($tfq$q-tf004-11$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Easy$tfq$, $tfq$single$tfq$, $tfq$What essential relationship does Terraform state record?$tfq$, $tfq$Provider binaries mapped to their download locations$tfq$, $tfq$Resource addresses mapped to real infrastructure objects$tfq$, $tfq$Variable names mapped to environment variable files$tfq$, $tfq$Module sources mapped to version-control branches$tfq$, NULL, NULL, 1, ARRAY[1]::INTEGER[], $tfq$State maps Terraform resource instances and their addresses to real remote objects, while also retaining metadata needed to plan and manage those objects.$tfq$, $tfq$tf004-state$tfq$),
  ($tfq$q-tf004-12$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Medium$tfq$, $tfq$single$tfq$, $tfq$Two engineers start operations against the same remote state at nearly the same time. Which backend capability reduces the risk of both operations writing state concurrently?$tfq$, $tfq$State locking$tfq$, $tfq$Provider aliasing$tfq$, $tfq$Output sensitivity$tfq$, $tfq$Module versioning$tfq$, NULL, NULL, 0, ARRAY[0]::INTEGER[], $tfq$State locking prevents supported operations from acquiring the same state for modification at the same time. The selected backend must support the relevant locking mechanism.$tfq$, $tfq$tf004-state$tfq$),
  ($tfq$q-tf004-13$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Easy$tfq$, $tfq$single$tfq$, $tfq$What is the immediate result of successfully importing an existing object to a Terraform resource address?$tfq$, $tfq$Terraform recreates the object using its default arguments$tfq$, $tfq$Terraform associates the existing object with the chosen address$tfq$, $tfq$Terraform generates a complete production-ready module automatically$tfq$, $tfq$Terraform moves the object into the account used by the provider$tfq$, NULL, NULL, 1, ARRAY[1]::INTEGER[], $tfq$Import binds an existing remote object to a selected Terraform resource address. The practitioner must still provide and review configuration that represents the desired managed object.$tfq$, $tfq$tf004-maintenance$tfq$),
  ($tfq$q-tf004-14$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Medium$tfq$, $tfq$single$tfq$, $tfq$A Terraform command fails without enough diagnostic detail. Which environment variable controls Terraform core log verbosity?$tfq$, $tfq$TF_INPUT$tfq$, $tfq$TF_DATA_DIR$tfq$, $tfq$TF_LOG$tfq$, $tfq$TF_VAR_name$tfq$, NULL, NULL, 2, ARRAY[2]::INTEGER[], $tfq$TF_LOG sets the Terraform core logging level, such as DEBUG or TRACE. Logs can contain sensitive information, so they should be enabled temporarily and handled carefully.$tfq$, $tfq$tf004-maintenance$tfq$),
  ($tfq$q-tf004-15$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Easy$tfq$, $tfq$single$tfq$, $tfq$Which collection of information is normally associated with an HCP Terraform workspace?$tfq$, $tfq$Provider source code, plugin releases, and Registry ownership$tfq$, $tfq$Configuration connection, variables, state, and run history$tfq$, $tfq$Cloud root credentials, billing data, and support tickets$tfq$, $tfq$Only a local plan file and the current CLI process$tfq$, NULL, NULL, 1, ARRAY[1]::INTEGER[], $tfq$An HCP Terraform workspace organizes the configuration source or workflow, variables, state, and run history used to manage a particular collection of infrastructure.$tfq$, $tfq$tf004-hcp$tfq$),
  ($tfq$q-tf004-16$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Medium$tfq$, $tfq$single$tfq$, $tfq$An organization must evaluate infrastructure changes against governance rules before an apply. Which HCP Terraform capability addresses this requirement?$tfq$, $tfq$Provider aliasing$tfq$, $tfq$Policy enforcement$tfq$, $tfq$Local state storage$tfq$, $tfq$Configuration formatting$tfq$, NULL, NULL, 1, ARRAY[1]::INTEGER[], $tfq$HCP Terraform policy enforcement evaluates runs against organizational policies at defined enforcement levels. Provider aliases, local state, and formatting do not provide governance decisions.$tfq$, $tfq$tf004-hcp$tfq$),
  ($tfq$q-tf004-17$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Medium$tfq$, $tfq$single$tfq$, $tfq$A resource must use the alternate AWS provider configuration declared with alias = "west". Which resource meta-argument selects it?$tfq$, $tfq$providers = aws.west$tfq$, $tfq$region = aws.west$tfq$, $tfq$provider = aws.west$tfq$, $tfq$source = aws.west$tfq$, NULL, NULL, 2, ARRAY[2]::INTEGER[], $tfq$A resource selects an alternate provider configuration with the provider meta-argument and the local provider reference, such as provider = aws.west.$tfq$, $tfq$tf004-fundamentals$tfq$),
  ($tfq$q-tf004-18$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Medium$tfq$, $tfq$single$tfq$, $tfq$What does sensitive = true on a Terraform variable guarantee?$tfq$, $tfq$The value is encrypted automatically in every possible backend$tfq$, $tfq$The value is omitted permanently from all state snapshots$tfq$, $tfq$The value is redacted from normal Terraform CLI presentation$tfq$, $tfq$The provider is prevented from receiving the variable value$tfq$, NULL, NULL, 2, ARRAY[2]::INTEGER[], $tfq$The sensitive flag redacts the value from normal CLI and UI presentation. It does not guarantee encryption or omission from state, so state and access to it must still be protected.$tfq$, $tfq$tf004-configuration$tfq$),
  ($tfq$q-tf004-19$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Medium$tfq$, $tfq$single$tfq$, $tfq$A resource replacement must minimize interruption when the remote API permits both objects to exist briefly. Which lifecycle setting is intended for this behavior?$tfq$, $tfq$prevent_destroy$tfq$, $tfq$ignore_changes$tfq$, $tfq$create_before_destroy$tfq$, $tfq$replace_triggered_by$tfq$, NULL, NULL, 2, ARRAY[2]::INTEGER[], $tfq$create_before_destroy requests creation of the replacement before deletion of the prior object. Provider and naming constraints can still prevent both objects from existing simultaneously.$tfq$, $tfq$tf004-configuration$tfq$),
  ($tfq$q-tf004-20$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Hard$tfq$, $tfq$multiple$tfq$, $tfq$Which two features can stop an operation when a custom condition is not satisfied? Select two.$tfq$, $tfq$A variable validation block$tfq$, $tfq$A resource precondition block$tfq$, $tfq$A dependency lock file checksum$tfq$, $tfq$A local backend path setting$tfq$, $tfq$A provider configuration alias$tfq$, NULL, 0, ARRAY[0, 1]::INTEGER[], $tfq$Variable validation rejects unsuitable input values, and a precondition prevents an operation when its required assumption is false. Lock checksums, backend paths, and aliases serve different purposes.$tfq$, $tfq$tf004-configuration$tfq$),
  ($tfq$q-tf004-21$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Medium$tfq$, $tfq$single$tfq$, $tfq$Why is for_each often safer than count for instances identified by stable names?$tfq$, $tfq$It identifies instances by keys instead of changing list positions$tfq$, $tfq$It prevents every instance from ever being replaced by Terraform$tfq$, $tfq$It automatically stores each instance in a separate state file$tfq$, $tfq$It lets one resource use providers from unrelated source addresses$tfq$, NULL, NULL, 0, ARRAY[0]::INTEGER[], $tfq$for_each uses map keys or set members in instance addresses. Stable keys can avoid the address shifting that may occur when count indexes an ordered list whose members change.$tfq$, $tfq$tf004-configuration$tfq$),
  ($tfq$q-tf004-22$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Medium$tfq$, $tfq$single$tfq$, $tfq$Where is a version constraint specified for a module sourced from a Terraform Registry?$tfq$, $tfq$In the backend block$tfq$, $tfq$In the module block$tfq$, $tfq$In the provider block$tfq$, $tfq$In the output block$tfq$, NULL, NULL, 1, ARRAY[1]::INTEGER[], $tfq$A Registry module call can use the version argument inside its module block. The version argument is not supported for every module source type.$tfq$, $tfq$tf004-modules$tfq$),
  ($tfq$q-tf004-23$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Medium$tfq$, $tfq$single$tfq$, $tfq$A team changes from the local backend to a configured remote backend and wants Terraform to copy the existing state. Which command is appropriate?$tfq$, $tfq$terraform state push -force$tfq$, $tfq$terraform init -migrate-state$tfq$, $tfq$terraform plan -refresh-only$tfq$, $tfq$terraform apply -replace-state$tfq$, NULL, NULL, 1, ARRAY[1]::INTEGER[], $tfq$terraform init -migrate-state reinitializes the working directory for the changed backend configuration and prompts to migrate existing state to the new backend.$tfq$, $tfq$tf004-state$tfq$),
  ($tfq$q-tf004-24$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Medium$tfq$, $tfq$single$tfq$, $tfq$An administrator changed a tag directly in the cloud console. The team wants to review updating state to match that remote change without modifying the remote object. Which plan mode should they use?$tfq$, $tfq$A destroy plan$tfq$, $tfq$A targeted plan$tfq$, $tfq$A refresh-only plan$tfq$, $tfq$A saved replacement plan$tfq$, NULL, NULL, 2, ARRAY[2]::INTEGER[], $tfq$Refresh-only mode proposes updates to Terraform state and root outputs so they match changes already made to remote objects, without proposing corrective changes to those objects.$tfq$, $tfq$tf004-state$tfq$),
  ($tfq$q-tf004-25$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Hard$tfq$, $tfq$single$tfq$, $tfq$A resource block is moved into a child module, but the real object must remain unchanged. Which configuration construct records the address change?$tfq$, $tfq$A check block$tfq$, $tfq$A moved block$tfq$, $tfq$A dynamic block$tfq$, $tfq$A terraform_data block$tfq$, NULL, NULL, 1, ARRAY[1]::INTEGER[], $tfq$A moved block maps the old resource address to the new address. Terraform can then preserve the existing object while recording the refactor in configuration.$tfq$, $tfq$tf004-state$tfq$),
  ($tfq$q-tf004-26$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Medium$tfq$, $tfq$multiple$tfq$, $tfq$Which two statements describe a safe import workflow? Select two.$tfq$, $tfq$Choose the destination resource address deliberately$tfq$, $tfq$Assume import creates a complete production configuration$tfq$, $tfq$Create and review configuration for the imported object$tfq$, $tfq$Expect import to move the object between cloud accounts$tfq$, $tfq$Delete the object remotely before running the import$tfq$, NULL, 0, ARRAY[0, 2]::INTEGER[], $tfq$The practitioner selects the Terraform address and supplies configuration that should manage the existing object. Import does not relocate or recreate the object, and generated configuration still requires review.$tfq$, $tfq$tf004-maintenance$tfq$),
  ($tfq$q-tf004-27$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Easy$tfq$, $tfq$multiple$tfq$, $tfq$Which two commands inspect Terraform state without changing resource addresses or removing records? Select two.$tfq$, $tfq$terraform state list$tfq$, $tfq$terraform state show$tfq$, $tfq$terraform state mv$tfq$, $tfq$terraform state rm$tfq$, $tfq$terraform state push$tfq$, NULL, 0, ARRAY[0, 1]::INTEGER[], $tfq$terraform state list displays tracked addresses and terraform state show displays attributes for a selected address. The mv, rm, and push operations can change state data.$tfq$, $tfq$tf004-maintenance$tfq$),
  ($tfq$q-tf004-28$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Hard$tfq$, $tfq$single$tfq$, $tfq$What distinguishes an ephemeral value from a value that is only marked sensitive?$tfq$, $tfq$An ephemeral value is always stored in a separate encrypted state file$tfq$, $tfq$An ephemeral value is omitted from Terraform plan and state artifacts$tfq$, $tfq$An ephemeral value can be referenced from every configuration context$tfq$, $tfq$An ephemeral value removes the need to protect provider log output$tfq$, NULL, NULL, 1, ARRAY[1]::INTEGER[], $tfq$Terraform omits ephemeral values from plan and state artifacts and restricts where they can be used. A sensitive value is normally redacted from display but can still be persisted in state.$tfq$, $tfq$tf004-configuration$tfq$),
  ($tfq$q-tf004-29$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Medium$tfq$, $tfq$single$tfq$, $tfq$What can a VCS-connected HCP Terraform workspace do when a relevant approved commit is pushed?$tfq$, $tfq$Queue a run based on the workspace VCS configuration$tfq$, $tfq$Apply changes while permanently skipping the plan stage$tfq$, $tfq$Overwrite the repository with the current remote state$tfq$, $tfq$Run every workspace in the organization unconditionally$tfq$, NULL, NULL, 0, ARRAY[0]::INTEGER[], $tfq$A VCS-connected workspace can detect relevant repository changes and queue runs according to its configuration. The normal run and approval controls still apply.$tfq$, $tfq$tf004-hcp$tfq$),
  ($tfq$q-tf004-30$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Hard$tfq$, $tfq$multiple$tfq$, $tfq$Which two HCP Terraform features directly support controlled team workflows? Select two.$tfq$, $tfq$Team-based workspace permissions$tfq$, $tfq$Removal of all historical state versions$tfq$, $tfq$Policy enforcement during run workflows$tfq$, $tfq$Credentials committed inside configuration files$tfq$, $tfq$Automatic bypass of mandatory run approvals$tfq$, NULL, 0, ARRAY[0, 2]::INTEGER[], $tfq$Team permissions control access to workspaces and actions, while policy enforcement evaluates proposed changes against organizational rules. The other choices weaken rather than support controlled collaboration.$tfq$, $tfq$tf004-hcp$tfq$),
  ($tfq$q-tf004-31$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Medium$tfq$, $tfq$single$tfq$, $tfq$A cloud object was changed manually after the last Terraform apply. What best describes Terraform's desired-state approach during the next plan?$tfq$, $tfq$Terraform ignores the object because it already exists remotely$tfq$, $tfq$Terraform compares configuration, state, and refreshed remote data$tfq$, $tfq$Terraform immediately changes the object before showing a plan$tfq$, $tfq$Terraform rewrites configuration to match every manual change$tfq$, NULL, NULL, 1, ARRAY[1]::INTEGER[], $tfq$Terraform creates a plan by reconciling the desired configuration with prior state and refreshed information about remote objects. It then proposes actions; it does not silently rewrite configuration or apply during planning.$tfq$, $tfq$tf004-iac$tfq$),
  ($tfq$q-tf004-32$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Medium$tfq$, $tfq$multiple$tfq$, $tfq$Which two entries belong in a required_providers declaration for a provider requirement? Select two.$tfq$, $tfq$The provider source address$tfq$, $tfq$The provider authentication token$tfq$, $tfq$An acceptable version constraint$tfq$, $tfq$The current remote resource IDs$tfq$, $tfq$The backend state-lock identifier$tfq$, NULL, 0, ARRAY[0, 2]::INTEGER[], $tfq$required_providers declares where a provider comes from and which versions are acceptable. Authentication belongs in provider configuration or secure external mechanisms, not in provider requirements.$tfq$, $tfq$tf004-fundamentals$tfq$),
  ($tfq$q-tf004-33$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Hard$tfq$, $tfq$single$tfq$, $tfq$A child module expects an alternate AWS configuration named aws.replica. How should the caller pass its own aws.west configuration to that child?$tfq$, $tfq$Set provider = aws.replica inside every child resource from the caller$tfq$, $tfq$Set providers = { aws.replica = aws.west } in the module block$tfq$, $tfq$Set aliases = { aws.west = aws.replica } in required_providers$tfq$, $tfq$Set source = aws.west in the child module output block$tfq$, NULL, NULL, 1, ARRAY[1]::INTEGER[], $tfq$The module call uses its providers map to associate the child module provider name with a provider configuration in the caller. The child must declare any configuration aliases it expects.$tfq$, $tfq$tf004-fundamentals$tfq$),
  ($tfq$q-tf004-34$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Medium$tfq$, $tfq$single$tfq$, $tfq$The configuration permits a newer provider version, but the dependency lock file retains an older selection. Which command asks Terraform to reconsider allowed provider selections?$tfq$, $tfq$terraform init -upgrade$tfq$, $tfq$terraform validate -upgrade$tfq$, $tfq$terraform plan -replace$tfq$, $tfq$terraform providers mirror$tfq$, NULL, NULL, 0, ARRAY[0]::INTEGER[], $tfq$terraform init -upgrade ignores the existing provider selections when choosing among versions allowed by the configured constraints, then updates the lock file as needed.$tfq$, $tfq$tf004-workflow$tfq$),
  ($tfq$q-tf004-35$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Medium$tfq$, $tfq$multiple$tfq$, $tfq$Which two statements correctly distinguish terraform fmt and terraform validate? Select two.$tfq$, $tfq$terraform fmt rewrites configuration into canonical style$tfq$, $tfq$terraform fmt confirms provider credentials can create resources$tfq$, $tfq$terraform validate checks configuration syntax and internal consistency$tfq$, $tfq$terraform validate applies safe formatting changes automatically$tfq$, $tfq$terraform validate confirms that a saved plan is still current$tfq$, NULL, 0, ARRAY[0, 2]::INTEGER[], $tfq$terraform fmt applies Terraform language style conventions. terraform validate checks whether a configuration is syntactically valid and internally consistent, but does not validate remote credentials or apply formatting.$tfq$, $tfq$tf004-workflow$tfq$),
  ($tfq$q-tf004-36$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Hard$tfq$, $tfq$single$tfq$, $tfq$A saved plan was created, but another successful apply changed the same workspace state before the saved plan was used. What should the team expect?$tfq$, $tfq$Terraform should reject the stale plan rather than apply it blindly$tfq$, $tfq$Terraform should merge both plans without recalculating dependencies$tfq$, $tfq$Terraform should delete the newer state and restore the saved state$tfq$, $tfq$Terraform should apply only resource creates from the older plan$tfq$, NULL, NULL, 0, ARRAY[0]::INTEGER[], $tfq$A saved plan is tied to the state and configuration context from which it was created. If the state has changed, Terraform detects that the plan is stale and requires a new plan.$tfq$, $tfq$tf004-workflow$tfq$),
  ($tfq$q-tf004-37$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Medium$tfq$, $tfq$single$tfq$, $tfq$A data source reads an image ID that is then assigned to a managed instance resource. What dependency behavior results from that reference?$tfq$, $tfq$Terraform infers that the data source must be read before planning the instance value$tfq$, $tfq$Terraform creates and later destroys the image represented by the data source$tfq$, $tfq$Terraform requires depends_on because data sources never create dependencies$tfq$, $tfq$Terraform copies the complete data source object into the instance state address$tfq$, NULL, NULL, 0, ARRAY[0]::INTEGER[], $tfq$The reference creates an implicit dependency in Terraform's graph. The data source reads information; it does not cause the referenced remote object to become managed by the resource lifecycle.$tfq$, $tfq$tf004-configuration$tfq$),
  ($tfq$q-tf004-38$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Hard$tfq$, $tfq$single$tfq$, $tfq$A variable has a default, a value in terraform.tfvars, and a value supplied with -var on the command line. Which value is used for that CLI-driven run?$tfq$, $tfq$The declared default because configuration has highest precedence$tfq$, $tfq$The terraform.tfvars value because it is loaded automatically$tfq$, $tfq$The command-line -var value because it has higher precedence$tfq$, $tfq$Terraform stops because the variable has more than one value source$tfq$, NULL, NULL, 2, ARRAY[2]::INTEGER[], $tfq$For the Terraform CLI variable-loading order, command-line -var and -var-file assignments take precedence over automatically loaded tfvars values and declared defaults.$tfq$, $tfq$tf004-configuration$tfq$),
  ($tfq$q-tf004-39$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Medium$tfq$, $tfq$single$tfq$, $tfq$A module needs a named collection whose values each contain a CIDR string and a Boolean public flag. Which type constraint best represents this input?$tfq$, $tfq$list(string)$tfq$, $tfq$map(object({ cidr = string, public = bool }))$tfq$, $tfq$tuple([string, bool])$tfq$, $tfq$set(map(string))$tfq$, NULL, NULL, 1, ARRAY[1]::INTEGER[], $tfq$A map provides stable names as keys, while each object enforces the cidr string and public Boolean attributes. The other types do not model a named collection of consistently shaped records.$tfq$, $tfq$tf004-configuration$tfq$),
  ($tfq$q-tf004-40$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Hard$tfq$, $tfq$single$tfq$, $tfq$Which expression returns only enabled service names from var.services, where each map value has an enabled Boolean attribute?$tfq$, $tfq$[for name, service in var.services : name if service.enabled]$tfq$, $tfq$[for name in var.services : service.enabled => name]$tfq$, $tfq$for_each(var.services, service.enabled, name)$tfq$, $tfq$filter(var.services[*].name, enabled = true)$tfq$, NULL, NULL, 0, ARRAY[0]::INTEGER[], $tfq$A for expression can transform each map element to its name and use an if clause to filter out values whose enabled attribute is false.$tfq$, $tfq$tf004-configuration$tfq$),
  ($tfq$q-tf004-41$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Hard$tfq$, $tfq$single$tfq$, $tfq$A resource must be created only when an input assumption is valid. Which custom condition is the closest fit?$tfq$, $tfq$A postcondition that is evaluated only after every future run$tfq$, $tfq$A precondition attached to the resource lifecycle$tfq$, $tfq$A check block that automatically changes the invalid input$tfq$, $tfq$A variable output that replaces the resource dependency$tfq$, NULL, NULL, 1, ARRAY[1]::INTEGER[], $tfq$A resource precondition checks an assumption before Terraform performs the associated resource operation and can stop the operation with a useful error message.$tfq$, $tfq$tf004-configuration$tfq$),
  ($tfq$q-tf004-42$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Hard$tfq$, $tfq$multiple$tfq$, $tfq$Which two statements about supported write-only resource arguments are correct? Select two.$tfq$, $tfq$Their configured values are not persisted in plan or state files$tfq$, $tfq$Every resource argument becomes write-only when marked sensitive$tfq$, $tfq$Provider support determines whether an argument is write-only$tfq$, $tfq$They can be read later with terraform state show$tfq$, $tfq$They remove the need to secure provider and Terraform logs$tfq$, NULL, 0, ARRAY[0, 2]::INTEGER[], $tfq$A provider schema defines supported write-only arguments, and Terraform does not persist their values in plan or state artifacts. They are different from sensitive values and do not make logging automatically safe.$tfq$, $tfq$tf004-configuration$tfq$),
  ($tfq$q-tf004-43$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Medium$tfq$, $tfq$single$tfq$, $tfq$A root module needs the subnet ID created inside a child module. What should form the child module interface for this value?$tfq$, $tfq$A child output referenced as module.network.subnet_id$tfq$, $tfq$A direct reference to the child resource local address$tfq$, $tfq$A backend block copied from the child into the caller$tfq$, $tfq$A provider lock entry exported by the child module$tfq$, NULL, NULL, 0, ARRAY[0]::INTEGER[], $tfq$The child module declares an output and the caller reads it through the module object. A caller cannot directly address a resource inside the child module as if it were in the same scope.$tfq$, $tfq$tf004-modules$tfq$),
  ($tfq$q-tf004-44$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Hard$tfq$, $tfq$single$tfq$, $tfq$A module block uses a local path source and also sets version = "~> 2.0". What is the problem?$tfq$, $tfq$Local modules cannot declare input variables or output values$tfq$, $tfq$The version argument applies to Registry module sources, not local paths$tfq$, $tfq$Local modules must be downloaded with terraform providers mirror$tfq$, $tfq$The version constraint must be moved into the provider configuration$tfq$, NULL, NULL, 1, ARRAY[1]::INTEGER[], $tfq$The module version argument is supported for Registry module sources. A local-path module uses the files at that path and is not selected through a Registry version constraint.$tfq$, $tfq$tf004-modules$tfq$),
  ($tfq$q-tf004-45$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Medium$tfq$, $tfq$multiple$tfq$, $tfq$Which two characteristics describe the default local backend? Select two.$tfq$, $tfq$It stores state on the local filesystem by default$tfq$, $tfq$It automatically provides shared remote collaboration$tfq$, $tfq$It performs Terraform operations on the local machine$tfq$, $tfq$It automatically encrypts state with HCP Terraform keys$tfq$, $tfq$It requires a cloud object-storage bucket for every workspace$tfq$, NULL, 0, ARRAY[0, 2]::INTEGER[], $tfq$The local backend stores state locally and executes operations locally. It does not by itself provide remote shared state, hosted encryption, or an object-storage requirement.$tfq$, $tfq$tf004-state$tfq$),
  ($tfq$q-tf004-46$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Hard$tfq$, $tfq$single$tfq$, $tfq$Why can a backend block not use normal input-variable references for all of its settings?$tfq$, $tfq$Backend initialization occurs before normal expression evaluation is available$tfq$, $tfq$Backends can only store state for configurations without any variables$tfq$, $tfq$Backend settings are copied from the provider dependency lock file$tfq$, $tfq$Terraform evaluates backend settings only after resources are applied$tfq$, NULL, NULL, 0, ARRAY[0]::INTEGER[], $tfq$Terraform must initialize the backend before it can perform the normal evaluation and planning workflow. Backend configuration therefore has restrictions and can also receive partial settings during initialization.$tfq$, $tfq$tf004-state$tfq$),
  ($tfq$q-tf004-47$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Hard$tfq$, $tfq$single$tfq$, $tfq$A team wants Terraform to stop managing an object without destroying the remote object, and wants the decision recorded in configuration. Which construct should they consider?$tfq$, $tfq$A removed block$tfq$, $tfq$A dynamic block$tfq$, $tfq$A check block$tfq$, $tfq$A terraform block$tfq$, NULL, NULL, 0, ARRAY[0]::INTEGER[], $tfq$A removed block can record that a resource is intentionally removed from Terraform management and, when configured not to destroy, preserve the remote object while removing it from state.$tfq$, $tfq$tf004-state$tfq$),
  ($tfq$q-tf004-48$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Hard$tfq$, $tfq$single$tfq$, $tfq$What advantage does an import block provide compared with relying only on a one-time terraform import CLI command?$tfq$, $tfq$It records the import request in reviewable configuration$tfq$, $tfq$It guarantees that generated configuration needs no review$tfq$, $tfq$It moves the imported object into the provider account$tfq$, $tfq$It prevents Terraform from refreshing the imported object$tfq$, NULL, NULL, 0, ARRAY[0]::INTEGER[], $tfq$An import block makes the intended import part of configuration, so it can be planned and reviewed with the rest of the change. Any generated or authored resource configuration still requires careful review.$tfq$, $tfq$tf004-maintenance$tfq$),
  ($tfq$q-tf004-49$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Medium$tfq$, $tfq$multiple$tfq$, $tfq$Which two statements correctly describe HCP Terraform projects and variable sets? Select two.$tfq$, $tfq$Projects can group related workspaces for organization and access control$tfq$, $tfq$Variable sets can provide reusable variables to selected workspaces or projects$tfq$, $tfq$Projects replace provider plugins with built-in cloud API clients$tfq$, $tfq$Variable sets are committed automatically to every linked repository$tfq$, $tfq$Projects force all workspaces to share one Terraform state file$tfq$, NULL, 0, ARRAY[0, 1]::INTEGER[], $tfq$Projects organize related workspaces and can support project-level permissions. Variable sets let teams reuse common variable definitions across selected scopes without forcing workspaces to share state.$tfq$, $tfq$tf004-hcp$tfq$),
  ($tfq$q-tf004-50$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Hard$tfq$, $tfq$multiple$tfq$, $tfq$Which two HCP Terraform features reduce manual coordination between connected workspaces and cloud credentials? Select two.$tfq$, $tfq$Run triggers that queue downstream workspace runs$tfq$, $tfq$Dynamic provider credentials issued for a run$tfq$, $tfq$A shared plaintext credentials file committed to VCS$tfq$, $tfq$One state file reused by every project workspace$tfq$, $tfq$Automatic approval of every policy failure$tfq$, NULL, 0, ARRAY[0, 1]::INTEGER[], $tfq$Run triggers coordinate dependent workspace runs, while dynamic provider credentials can issue short-lived credentials for an HCP Terraform run. The other options weaken isolation or governance.$tfq$, $tfq$tf004-hcp$tfq$),
  ($tfq$q-tf004-51$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Easy$tfq$, $tfq$single$tfq$, $tfq$Which statement best describes infrastructure as code in a Terraform workflow?$tfq$, $tfq$Infrastructure is defined in machine-readable configuration and managed through repeatable operations$tfq$, $tfq$Infrastructure is created manually and Terraform records screenshots of the completed environment$tfq$, $tfq$Infrastructure is stored entirely inside provider plugins rather than in configuration files$tfq$, $tfq$Infrastructure is changed through tickets while Terraform monitors the approval queue$tfq$, NULL, NULL, 0, ARRAY[0]::INTEGER[], $tfq$Infrastructure as code represents desired infrastructure in machine-readable files that can be reviewed, versioned, and used in repeatable workflows. It does not mean recording or automating a manual ticket process.$tfq$, $tfq$tf004-iac$tfq$),
  ($tfq$q-tf004-52$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Medium$tfq$, $tfq$multiple$tfq$, $tfq$Which two outcomes are direct advantages of an infrastructure-as-code workflow? Select two.$tfq$, $tfq$Changes can be reviewed through version-control history$tfq$, $tfq$Identical configuration always produces identical provider-generated IDs$tfq$, $tfq$Environments can be created through a repeatable process$tfq$, $tfq$Remote users are prevented from making manual changes$tfq$, $tfq$Provider API outages no longer affect infrastructure changes$tfq$, NULL, 0, ARRAY[0, 2]::INTEGER[], $tfq$Version control makes configuration changes auditable and reviewable, while reusable configuration supports repeatable environment creation. IaC cannot guarantee generated IDs, eliminate API outages, or technically prevent all manual changes.$tfq$, $tfq$tf004-iac$tfq$),
  ($tfq$q-tf004-53$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Medium$tfq$, $tfq$single$tfq$, $tfq$A company manages on-premises virtualization, a public cloud, and a SaaS monitoring platform. What allows one Terraform workflow to cover this hybrid environment?$tfq$, $tfq$A single state file converts every platform into the same service API$tfq$, $tfq$Separate providers expose each platform through Terraform resources and data sources$tfq$, $tfq$The local backend copies all on-premises objects into the public cloud$tfq$, $tfq$Terraform modules remove the need for platform-specific authentication$tfq$, NULL, NULL, 1, ARRAY[1]::INTEGER[], $tfq$Terraform uses platform-specific providers behind a consistent configuration and workflow model. Each provider still communicates with its own API and requires appropriate authentication.$tfq$, $tfq$tf004-iac$tfq$),
  ($tfq$q-tf004-54$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Hard$tfq$, $tfq$single$tfq$, $tfq$A root module permits AWS provider versions >= 5.0 and < 6.0, while a child module requires >= 5.30. Which versions can Terraform select?$tfq$, $tfq$Any version from 5.0 upward because root constraints override child constraints$tfq$, $tfq$A version from 5.30 up to, but not including, 6.0$tfq$, $tfq$Exactly version 5.30 because the child module is more specific$tfq$, $tfq$No version because different modules cannot constrain one provider$tfq$, NULL, NULL, 1, ARRAY[1]::INTEGER[], $tfq$Terraform selects one provider version compatible with every module requirement. The intersection is version 5.30 or newer but still below 6.0; the lock file can then record the selected version.$tfq$, $tfq$tf004-fundamentals$tfq$),
  ($tfq$q-tf004-55$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Medium$tfq$, $tfq$single$tfq$, $tfq$What information does a Terraform provider schema supply to Terraform Core?$tfq$, $tfq$Supported resource and data-source types with their arguments and attributes$tfq$, $tfq$The complete desired configuration for every resource in the workspace$tfq$, $tfq$The team permissions used to approve runs in HCP Terraform$tfq$, $tfq$The version-control history used to calculate infrastructure drift$tfq$, NULL, NULL, 0, ARRAY[0]::INTEGER[], $tfq$A provider plugin exposes schemas and implements operations for its resource and data-source types. Terraform Core uses that information to validate configuration and coordinate planning and applying.$tfq$, $tfq$tf004-fundamentals$tfq$),
  ($tfq$q-tf004-56$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Hard$tfq$, $tfq$multiple$tfq$, $tfq$A root module configures default aws and aliased aws.dr providers. Which two statements are correct? Select two.$tfq$, $tfq$A resource can select aws.dr with its provider meta-argument$tfq$, $tfq$Every child module automatically inherits all aliased configurations$tfq$, $tfq$A module call can explicitly map a child provider name to aws.dr$tfq$, $tfq$The alias changes the provider source address to a new provider$tfq$, $tfq$Each alias requires a separate provider version in the lock file$tfq$, NULL, 0, ARRAY[0, 2]::INTEGER[], $tfq$Resources can select an alias with provider = aws.dr, and callers can pass configurations through a module providers map. Aliases are configurations of the same provider and are not all inherited automatically.$tfq$, $tfq$tf004-fundamentals$tfq$),
  ($tfq$q-tf004-57$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Medium$tfq$, $tfq$single$tfq$, $tfq$Why does Terraform normally refresh information about managed objects before proposing changes?$tfq$, $tfq$To update the dependency lock file with newer provider checksums$tfq$, $tfq$To compare recorded state with current remote object information$tfq$, $tfq$To rewrite all variable values from the provider configuration$tfq$, $tfq$To import every remote object that matches a resource type$tfq$, NULL, NULL, 1, ARRAY[1]::INTEGER[], $tfq$Refreshing lets Terraform compare prior state and current remote values before calculating the plan. It does not discover and import unrelated objects or update provider dependencies.$tfq$, $tfq$tf004-fundamentals$tfq$),
  ($tfq$q-tf004-58$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Easy$tfq$, $tfq$single$tfq$, $tfq$Which sequence most closely follows the core Terraform workflow for a new configuration?$tfq$, $tfq$Write, initialize, plan, review, and apply$tfq$, $tfq$Apply, initialize, write, review, and destroy$tfq$, $tfq$Initialize, destroy, import, format, and apply$tfq$, $tfq$Write, apply, initialize, refresh, and review$tfq$, NULL, NULL, 0, ARRAY[0]::INTEGER[], $tfq$The core workflow is to write configuration, initialize the working directory, generate and review a plan, and then apply the approved changes. Validation and formatting support this workflow.$tfq$, $tfq$tf004-workflow$tfq$),
  ($tfq$q-tf004-59$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Medium$tfq$, $tfq$single$tfq$, $tfq$A backend configuration changed, and the team wants to accept the new configuration without copying state from the previously configured backend. Which initialization option fits?$tfq$, $tfq$terraform init -upgrade$tfq$, $tfq$terraform init -reconfigure$tfq$, $tfq$terraform init -migrate-state$tfq$, $tfq$terraform init -get=false$tfq$, NULL, NULL, 1, ARRAY[1]::INTEGER[], $tfq$terraform init -reconfigure disregards the previously saved backend configuration and initializes using the new settings without performing state migration. Migration is a distinct, deliberate operation.$tfq$, $tfq$tf004-workflow$tfq$),
  ($tfq$q-tf004-60$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Medium$tfq$, $tfq$multiple$tfq$, $tfq$Which two statements about terraform validate are correct? Select two.$tfq$, $tfq$It checks configuration syntax and internal consistency$tfq$, $tfq$It verifies that cloud credentials can create every resource$tfq$, $tfq$It can be run without contacting configured remote services$tfq$, $tfq$It changes remote objects to match the configuration$tfq$, $tfq$It replaces the need to review an execution plan$tfq$, NULL, 0, ARRAY[0, 2]::INTEGER[], $tfq$terraform validate checks syntax and internal consistency and does not validate remote APIs or credentials. An initialized directory may be needed for providers and modules, but validation itself does not plan or apply infrastructure.$tfq$, $tfq$tf004-workflow$tfq$),
  ($tfq$q-tf004-61$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Hard$tfq$, $tfq$single$tfq$, $tfq$In automation, terraform plan -detailed-exitcode returns exit code 2. What does that result mean?$tfq$, $tfq$The plan failed because configuration could not be parsed$tfq$, $tfq$The plan succeeded and proposed at least one change$tfq$, $tfq$The plan succeeded and found no infrastructure changes$tfq$, $tfq$The plan was applied and state was updated successfully$tfq$, NULL, NULL, 1, ARRAY[1]::INTEGER[], $tfq$With -detailed-exitcode, 0 means success with an empty diff, 1 means an error, and 2 means success with proposed changes. The command still only creates a plan.$tfq$, $tfq$tf004-workflow$tfq$),
  ($tfq$q-tf004-62$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Medium$tfq$, $tfq$single$tfq$, $tfq$What happens when terraform apply is run without supplying a previously saved plan?$tfq$, $tfq$Terraform creates a new plan and normally asks for approval before applying it$tfq$, $tfq$Terraform applies the most recent plan found anywhere in the working directory$tfq$, $tfq$Terraform skips planning and sends configuration directly to each provider$tfq$, $tfq$Terraform applies only output changes and leaves resources unchanged$tfq$, NULL, NULL, 0, ARRAY[0]::INTEGER[], $tfq$Without a saved plan file, terraform apply creates a fresh execution plan and normally asks the user to approve it. A saved plan is required when the exact earlier plan must be applied.$tfq$, $tfq$tf004-workflow$tfq$),
  ($tfq$q-tf004-63$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Medium$tfq$, $tfq$single$tfq$, $tfq$How does terraform destroy determine which managed objects to propose for deletion?$tfq$, $tfq$It proposes destroy actions for objects represented by the current configuration and state$tfq$, $tfq$It lists every object accessible through the configured provider credentials$tfq$, $tfq$It deletes provider plugins and assumes remote objects are deleted separately$tfq$, $tfq$It removes only objects created during the immediately preceding apply$tfq$, NULL, NULL, 0, ARRAY[0]::INTEGER[], $tfq$terraform destroy is a convenience form of planning and applying a destroy operation for managed objects in the current configuration and state. It does not enumerate every accessible account resource.$tfq$, $tfq$tf004-workflow$tfq$),
  ($tfq$q-tf004-64$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Easy$tfq$, $tfq$single$tfq$, $tfq$What is the effect of running terraform fmt -recursive in a configuration directory?$tfq$, $tfq$It formats Terraform files in the directory and its subdirectories$tfq$, $tfq$It validates remote provider credentials in every child module$tfq$, $tfq$It generates and saves one plan for each configuration file$tfq$, $tfq$It upgrades modules and providers to their newest versions$tfq$, NULL, NULL, 0, ARRAY[0]::INTEGER[], $tfq$terraform fmt rewrites Terraform configuration into canonical style, and -recursive includes subdirectories. Formatting does not validate credentials, produce plans, or upgrade dependencies.$tfq$, $tfq$tf004-workflow$tfq$),
  ($tfq$q-tf004-65$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Medium$tfq$, $tfq$single$tfq$, $tfq$A configuration reads the current AWS account identity and creates a storage bucket. Which pairing uses the appropriate block types?$tfq$, $tfq$Use a data block for the account identity and a resource block for the bucket$tfq$, $tfq$Use a resource block for the account identity and a data block for the bucket$tfq$, $tfq$Use output blocks for both because neither value belongs in configuration$tfq$, $tfq$Use import blocks for both so Terraform can discover their schemas$tfq$, NULL, NULL, 0, ARRAY[0]::INTEGER[], $tfq$A data source reads existing information such as the current caller identity, while a resource block declares an object whose lifecycle Terraform should manage.$tfq$, $tfq$tf004-configuration$tfq$),
  ($tfq$q-tf004-66$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Medium$tfq$, $tfq$single$tfq$, $tfq$A subnet argument references aws_vpc.main.id. What additional behavior does Terraform derive from that reference?$tfq$, $tfq$An implicit dependency that places the VPC before the subnet$tfq$, $tfq$A provider alias that moves the subnet into another region$tfq$, $tfq$A lifecycle rule that prevents the VPC from being replaced$tfq$, $tfq$A state lock that applies only to those two resources$tfq$, NULL, NULL, 0, ARRAY[0]::INTEGER[], $tfq$The attribute reference both supplies the VPC ID and creates an implicit graph dependency. Terraform can therefore order the VPC operation before the dependent subnet operation.$tfq$, $tfq$tf004-configuration$tfq$),
  ($tfq$q-tf004-67$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Medium$tfq$, $tfq$multiple$tfq$, $tfq$Which two statements about root-module output values are correct? Select two.$tfq$, $tfq$They can expose selected values after an apply$tfq$, $tfq$They automatically become input variables in every child module$tfq$, $tfq$Sensitive outputs are redacted in normal CLI output$tfq$, $tfq$They are never recorded in Terraform state$tfq$, $tfq$They can only refer to literal string values$tfq$, NULL, 0, ARRAY[0, 2]::INTEGER[], $tfq$Root outputs expose selected values and can be marked sensitive to redact normal display. Output values are stored in state, can use expressions of many types, and do not automatically become child inputs.$tfq$, $tfq$tf004-configuration$tfq$),
  ($tfq$q-tf004-68$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Medium$tfq$, $tfq$single$tfq$, $tfq$A variable must contain exactly three values in a fixed order: a string name, a number port, and a Boolean enabled flag. Which type best describes it?$tfq$, $tfq$tuple([string, number, bool])$tfq$, $tfq$list(string)$tfq$, $tfq$map(any)$tfq$, $tfq$set(object({ value = string }))$tfq$, NULL, NULL, 0, ARRAY[0]::INTEGER[], $tfq$A tuple can require a fixed number of elements with a distinct type at each position. Lists and sets contain elements of a common type, while the proposed map has no fixed positional structure.$tfq$, $tfq$tf004-configuration$tfq$),
  ($tfq$q-tf004-69$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Medium$tfq$, $tfq$single$tfq$, $tfq$Which expression safely selects var.custom_name when it is not null and otherwise uses the string "default-name"?$tfq$, $tfq$var.custom_name != null ? var.custom_name : "default-name"$tfq$, $tfq$if var.custom_name then var.custom_name else "default-name"$tfq$, $tfq$select(var.custom_name, null, "default-name")$tfq$, $tfq$var.custom_name || "default-name"$tfq$, NULL, NULL, 0, ARRAY[0]::INTEGER[], $tfq$Terraform conditional expressions use condition ? true_value : false_value. Both result expressions must have compatible types so Terraform can determine the expression type.$tfq$, $tfq$tf004-configuration$tfq$),
  ($tfq$q-tf004-70$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Hard$tfq$, $tfq$single$tfq$, $tfq$A service must be restarted after a policy resource changes, but none of the service arguments reference that policy. How can the hidden ordering requirement be declared?$tfq$, $tfq$Add the policy resource to the service depends_on list$tfq$, $tfq$Add the policy ID to the provider dependency lock file$tfq$, $tfq$Move both resources into separate CLI workspaces$tfq$, $tfq$Mark the service output as sensitive and ephemeral$tfq$, NULL, NULL, 0, ARRAY[0]::INTEGER[], $tfq$depends_on declares a real dependency that Terraform cannot infer from value references. It should be used carefully because it can make plans more conservative than necessary.$tfq$, $tfq$tf004-configuration$tfq$),
  ($tfq$q-tf004-71$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Hard$tfq$, $tfq$single$tfq$, $tfq$A team wants to test a deployed endpoint after apply but receive a warning rather than block the operation when the endpoint check fails. Which feature is designed for this?$tfq$, $tfq$A resource precondition$tfq$, $tfq$An input-variable validation$tfq$, $tfq$A check block assertion$tfq$, $tfq$A provider version constraint$tfq$, NULL, NULL, 2, ARRAY[2]::INTEGER[], $tfq$A check block validates infrastructure outside the normal resource lifecycle and reports a warning when its assertion fails. Preconditions and variable validation can block the associated operation.$tfq$, $tfq$tf004-configuration$tfq$),
  ($tfq$q-tf004-72$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Medium$tfq$, $tfq$multiple$tfq$, $tfq$Which two practices reduce the risk of exposing secrets in Terraform workflows? Select two.$tfq$, $tfq$Use short-lived credentials from a trusted secrets system where possible$tfq$, $tfq$Commit plaintext tfvars files so every runner uses identical values$tfq$, $tfq$Protect state storage with encryption and restricted access$tfq$, $tfq$Print sensitive outputs after every apply for audit purposes$tfq$, $tfq$Enable TRACE logging permanently in shared automation$tfq$, NULL, 0, ARRAY[0, 2]::INTEGER[], $tfq$Short-lived credentials and protected state reduce secret exposure and persistence. Plaintext files, displayed outputs, and verbose logs can expose secrets and should not be treated as secure distribution methods.$tfq$, $tfq$tf004-configuration$tfq$),
  ($tfq$q-tf004-73$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Hard$tfq$, $tfq$single$tfq$, $tfq$A platform automatically changes one resource tag after creation, and Terraform should not propose updating only that tag on later plans. Which lifecycle setting is appropriate?$tfq$, $tfq$ignore_changes for the specific tag attribute path$tfq$, $tfq$create_before_destroy for the complete resource$tfq$, $tfq$prevent_destroy for the provider configuration$tfq$, $tfq$replace_triggered_by for every tag in the account$tfq$, NULL, NULL, 0, ARRAY[0]::INTEGER[], $tfq$ignore_changes can tell Terraform to disregard selected remote attribute changes during update planning. Terraform still considers the configured value when initially creating the object.$tfq$, $tfq$tf004-configuration$tfq$),
  ($tfq$q-tf004-74$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Hard$tfq$, $tfq$single$tfq$, $tfq$What is the primary purpose of a dynamic block inside a resource?$tfq$, $tfq$Generate repeated nested blocks from a collection or expression$tfq$, $tfq$Choose provider versions dynamically during terraform apply$tfq$, $tfq$Create new resource types that the provider does not implement$tfq$, $tfq$Read arbitrary remote objects without declaring a data source$tfq$, NULL, NULL, 0, ARRAY[0]::INTEGER[], $tfq$A dynamic block generates repeated nested configuration blocks using collection data. It cannot generate top-level resource blocks or create provider capabilities that do not exist.$tfq$, $tfq$tf004-configuration$tfq$),
  ($tfq$q-tf004-75$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Hard$tfq$, $tfq$single$tfq$, $tfq$A module input uses object({ name = string, description = optional(string, "managed") }). What happens when a caller omits description?$tfq$, $tfq$Terraform supplies the default string "managed" for that attribute$tfq$, $tfq$Terraform rejects the object because every object attribute is required$tfq$, $tfq$Terraform removes the complete object from the module call$tfq$, $tfq$Terraform converts the description attribute into an empty list$tfq$, NULL, NULL, 0, ARRAY[0]::INTEGER[], $tfq$The optional type modifier makes the attribute optional and the second argument supplies its default. The remaining name attribute is still required and must be a string.$tfq$, $tfq$tf004-configuration$tfq$),
  ($tfq$q-tf004-76$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Hard$tfq$, $tfq$single$tfq$, $tfq$A Vault data source returns a secret and a normal resource argument consumes it. What should the team assume unless supported ephemeral and write-only features prevent persistence?$tfq$, $tfq$The secret may be recorded in Terraform state and state access must be protected$tfq$, $tfq$Vault guarantees the value cannot appear in state under any circumstances$tfq$, $tfq$Terraform replaces the secret with its Vault path before writing state$tfq$, $tfq$The provider lock file encrypts the value with the Vault provider checksum$tfq$, NULL, NULL, 0, ARRAY[0]::INTEGER[], $tfq$Reading a secret from Vault does not automatically keep it out of state when a managed resource stores that value. Teams must understand provider behavior and protect state or use supported non-persistent mechanisms.$tfq$, $tfq$tf004-configuration$tfq$),
  ($tfq$q-tf004-77$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Medium$tfq$, $tfq$single$tfq$, $tfq$A module source is git::https://example.com/network.git?ref=v2.1.0. What does the ref parameter select?$tfq$, $tfq$The Git revision Terraform should retrieve for the module source$tfq$, $tfq$The provider configuration alias used by module resources$tfq$, $tfq$The Terraform CLI workspace that will hold module state$tfq$, $tfq$The output value returned after the module has been applied$tfq$, NULL, NULL, 0, ARRAY[0]::INTEGER[], $tfq$For a Git module source, ref selects a branch, tag, or commit understood by Git. This is separate from the Registry module version argument and provider configuration.$tfq$, $tfq$tf004-modules$tfq$),
  ($tfq$q-tf004-78$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Medium$tfq$, $tfq$single$tfq$, $tfq$Can a root module directly reference aws_subnet.private.id when that resource is declared inside a child module named network?$tfq$, $tfq$No; the child must expose the value through an output referenced from module.network$tfq$, $tfq$Yes; every resource address is automatically global across all module scopes$tfq$, $tfq$Yes; but only after copying the child state file into the root directory$tfq$, $tfq$No; child-module resource attributes can never be used outside that module$tfq$, NULL, NULL, 0, ARRAY[0]::INTEGER[], $tfq$Resource names are scoped to their module. The child exposes selected values through outputs, which the caller reads through expressions such as module.network.subnet_id.$tfq$, $tfq$tf004-modules$tfq$),
  ($tfq$q-tf004-79$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Medium$tfq$, $tfq$multiple$tfq$, $tfq$Which two arguments are part of a normal child module call? Select two.$tfq$, $tfq$A source identifying where Terraform obtains the module$tfq$, $tfq$Values assigned to input variables declared by the child$tfq$, $tfq$A state file copied from the child module repository$tfq$, $tfq$A new Terraform executable compiled for the child module$tfq$, $tfq$Remote resource IDs for every object the child might create$tfq$, NULL, 0, ARRAY[0, 1]::INTEGER[], $tfq$A module block declares its source and assigns values to the child module input interface. Terraform manages module resources in the calling configuration state; callers do not copy a separate child state file.$tfq$, $tfq$tf004-modules$tfq$),
  ($tfq$q-tf004-80$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Hard$tfq$, $tfq$single$tfq$, $tfq$A Registry module constraint is ~> 3.2.1. Which module version is compatible with that constraint?$tfq$, $tfq$3.2.9$tfq$, $tfq$3.3.0$tfq$, $tfq$4.0.0$tfq$, $tfq$3.1.8$tfq$, NULL, NULL, 0, ARRAY[0]::INTEGER[], $tfq$The pessimistic constraint ~> 3.2.1 permits newer patch releases within 3.2 but not 3.3.0 or later. It also does not permit an older 3.1 release.$tfq$, $tfq$tf004-modules$tfq$),
  ($tfq$q-tf004-81$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Hard$tfq$, $tfq$single$tfq$, $tfq$A reusable child module requires the AWS provider. Where should the AWS region normally be configured?$tfq$, $tfq$In a provider configuration in the root module and inherited or passed to the child$tfq$, $tfq$In a provider block inside every reusable child module that uses AWS$tfq$, $tfq$In the child module dependency lock file as a provider checksum field$tfq$, $tfq$In a child output so the provider reads it after resources are created$tfq$, NULL, NULL, 0, ARRAY[0]::INTEGER[], $tfq$Provider configurations belong in the root module and can be inherited or explicitly passed. Each child still declares provider requirements, but reusable children should not own provider configurations.$tfq$, $tfq$tf004-modules$tfq$),
  ($tfq$q-tf004-82$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Medium$tfq$, $tfq$single$tfq$, $tfq$Two sibling child modules need to share a VPC ID. What is the clearest module-composition pattern?$tfq$, $tfq$Pass one module's VPC ID output into the other module's input$tfq$, $tfq$Let both modules manage the same VPC resource address independently$tfq$, $tfq$Copy the VPC state entry into both child module directories$tfq$, $tfq$Place the VPC ID in the provider dependency lock file$tfq$, NULL, NULL, 0, ARRAY[0]::INTEGER[], $tfq$Module composition uses explicit outputs and inputs to connect modules. One real object should not be independently managed at multiple Terraform addresses.$tfq$, $tfq$tf004-modules$tfq$),
  ($tfq$q-tf004-83$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Easy$tfq$, $tfq$single$tfq$, $tfq$With no backend block configured, where does the default local backend normally store state?$tfq$, $tfq$In terraform.tfstate in the working directory$tfq$, $tfq$In .terraform.lock.hcl beside the provider checksums$tfq$, $tfq$In the public Terraform Registry for the selected module$tfq$, $tfq$In a provider-specific object selected during terraform plan$tfq$, NULL, NULL, 0, ARRAY[0]::INTEGER[], $tfq$The default local backend normally stores workspace state in a local terraform.tfstate file. That is separate from the dependency lock file and provider or Registry services.$tfq$, $tfq$tf004-state$tfq$),
  ($tfq$q-tf004-84$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Medium$tfq$, $tfq$single$tfq$, $tfq$A backend reports that the state is locked by another active operation. What is the safest first response?$tfq$, $tfq$Confirm whether the other operation is still running before taking further action$tfq$, $tfq$Delete the state file so Terraform creates an unlocked replacement$tfq$, $tfq$Run force-unlock immediately without checking the lock owner$tfq$, $tfq$Change the resource names so the current operation uses a different lock$tfq$, NULL, NULL, 0, ARRAY[0]::INTEGER[], $tfq$A lock normally indicates another state-changing operation. The team should first identify and allow the active operation to finish; forcing a lock can permit concurrent writes and state corruption.$tfq$, $tfq$tf004-state$tfq$),
  ($tfq$q-tf004-85$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Medium$tfq$, $tfq$multiple$tfq$, $tfq$Which two benefits can a suitable remote backend provide to a team? Select two.$tfq$, $tfq$A shared location for Terraform state$tfq$, $tfq$State locking when the selected backend supports it$tfq$, $tfq$Automatic creation of every resource in configuration$tfq$, $tfq$Provider authentication without any credentials$tfq$, $tfq$Guaranteed prevention of all manual infrastructure changes$tfq$, NULL, 0, ARRAY[0, 1]::INTEGER[], $tfq$A remote backend can centralize state and may provide locking, depending on backend capabilities. It does not create resources by itself, replace provider authentication, or prevent drift.$tfq$, $tfq$tf004-state$tfq$),
  ($tfq$q-tf004-86$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Hard$tfq$, $tfq$single$tfq$, $tfq$A remote object was deleted manually, but its resource remains in configuration and state. What will a normal Terraform plan generally propose?$tfq$, $tfq$Create a replacement object so reality matches the configuration$tfq$, $tfq$Remove the resource block automatically from configuration$tfq$, $tfq$Ignore the missing object because it remains recorded in state$tfq$, $tfq$Import an unrelated object of the same provider resource type$tfq$, NULL, NULL, 0, ARRAY[0]::INTEGER[], $tfq$After refresh detects that the managed object is missing, Terraform normally plans to create it again because the resource remains in desired configuration.$tfq$, $tfq$tf004-state$tfq$),
  ($tfq$q-tf004-87$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Hard$tfq$, $tfq$single$tfq$, $tfq$When is a moved block normally preferable to running terraform state mv as a one-time local command?$tfq$, $tfq$When the address refactor should be recorded and repeatable for other copies of the configuration$tfq$, $tfq$When Terraform must delete the real object before assigning its new address$tfq$, $tfq$When the provider version must be upgraded without changing the lock file$tfq$, $tfq$When remote state should be converted permanently into local state$tfq$, NULL, NULL, 0, ARRAY[0]::INTEGER[], $tfq$A moved block documents the address transition in version-controlled configuration, allowing other users and automation to apply the same refactor safely.$tfq$, $tfq$tf004-state$tfq$),
  ($tfq$q-tf004-88$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Medium$tfq$, $tfq$single$tfq$, $tfq$What does creating a new Terraform CLI workspace with a backend normally provide?$tfq$, $tfq$A separate state instance for the same configuration$tfq$, $tfq$A separate copy of every Terraform configuration file$tfq$, $tfq$A new HCP Terraform organization and project$tfq$, $tfq$A new provider plugin version for each resource type$tfq$, NULL, NULL, 0, ARRAY[0]::INTEGER[], $tfq$CLI workspaces allow multiple state instances for one configuration in a supporting backend. They are distinct from HCP Terraform workspaces and do not duplicate the configuration files.$tfq$, $tfq$tf004-state$tfq$),
  ($tfq$q-tf004-89$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Hard$tfq$, $tfq$multiple$tfq$, $tfq$Which two statements describe safe use of terraform force-unlock? Select two.$tfq$, $tfq$Use the lock ID reported by the failed locking operation$tfq$, $tfq$Confirm that no active operation still owns the lock$tfq$, $tfq$Use it routinely before every automated terraform plan$tfq$, $tfq$Expect it to modify remote infrastructure immediately$tfq$, $tfq$Use it to replace a lost state file with configuration defaults$tfq$, NULL, 0, ARRAY[0, 1]::INTEGER[], $tfq$force-unlock requires the specific lock ID and should be used only after verifying that the lock is stale. It removes a state lock; it does not rebuild state or directly change infrastructure.$tfq$, $tfq$tf004-state$tfq$),
  ($tfq$q-tf004-90$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Medium$tfq$, $tfq$single$tfq$, $tfq$Before running terraform import aws_instance.web i-0123456789, what must exist in configuration?$tfq$, $tfq$A resource block at the destination address aws_instance.web$tfq$, $tfq$An output named i-0123456789 containing the instance attributes$tfq$, $tfq$A data block that already owns the remote instance lifecycle$tfq$, $tfq$A moved block from the instance ID to the destination address$tfq$, NULL, NULL, 0, ARRAY[0]::INTEGER[], $tfq$The traditional terraform import command binds a remote object to an existing resource address in configuration. The resource arguments must then be reviewed so future plans manage it correctly.$tfq$, $tfq$tf004-maintenance$tfq$),
  ($tfq$q-tf004-91$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Medium$tfq$, $tfq$single$tfq$, $tfq$Which command displays the attributes currently recorded for the state address module.network.aws_vpc.main?$tfq$, $tfq$terraform state show module.network.aws_vpc.main$tfq$, $tfq$terraform output module.network.aws_vpc.main$tfq$, $tfq$terraform providers show module.network.aws_vpc.main$tfq$, $tfq$terraform validate module.network.aws_vpc.main$tfq$, NULL, NULL, 0, ARRAY[0]::INTEGER[], $tfq$terraform state show accepts one resource instance address and displays its attributes from state. It is an inspection command and does not refresh or change the remote object.$tfq$, $tfq$tf004-maintenance$tfq$),
  ($tfq$q-tf004-92$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Medium$tfq$, $tfq$multiple$tfq$, $tfq$Which two practices are appropriate when collecting verbose Terraform diagnostic logs? Select two.$tfq$, $tfq$Set TF_LOG to an appropriate temporary log level$tfq$, $tfq$Use TF_LOG_PATH when logs should be written to a file$tfq$, $tfq$Publish the raw logs because Terraform always redacts secrets$tfq$, $tfq$Leave TRACE logging enabled permanently in shared automation$tfq$, $tfq$Store the log inside the provider dependency lock file$tfq$, NULL, 0, ARRAY[0, 1]::INTEGER[], $tfq$TF_LOG controls verbosity and TF_LOG_PATH can direct output to a file. Diagnostic logs may contain sensitive information, so logging should be temporary and its output protected.$tfq$, $tfq$tf004-maintenance$tfq$),
  ($tfq$q-tf004-93$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Hard$tfq$, $tfq$single$tfq$, $tfq$A configuration contains an import block with to = aws_s3_bucket.logs and id = "existing-logs". When does Terraform perform the import?$tfq$, $tfq$As part of applying a plan that includes the import action$tfq$, $tfq$Immediately when the configuration file is saved to disk$tfq$, $tfq$Only after the import block is removed from configuration$tfq$, $tfq$During terraform fmt before provider initialization occurs$tfq$, NULL, NULL, 0, ARRAY[0]::INTEGER[], $tfq$Import blocks make import actions plannable and reviewable. Terraform performs the import during apply after the plan is approved, rather than when files are saved or formatted.$tfq$, $tfq$tf004-maintenance$tfq$),
  ($tfq$q-tf004-94$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Hard$tfq$, $tfq$single$tfq$, $tfq$What is the effect of terraform state rm aws_s3_bucket.archive when the remote bucket still exists?$tfq$, $tfq$Terraform forgets the state binding without deleting the remote bucket$tfq$, $tfq$Terraform deletes the bucket but retains its address in state$tfq$, $tfq$Terraform imports the bucket into a new automatically chosen address$tfq$, $tfq$Terraform encrypts the bucket record and hides it from state list$tfq$, NULL, NULL, 0, ARRAY[0]::INTEGER[], $tfq$terraform state rm removes the binding from state and does not destroy the remote object. If the resource block remains, a later plan may propose creating another object.$tfq$, $tfq$tf004-maintenance$tfq$),
  ($tfq$q-tf004-95$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Easy$tfq$, $tfq$single$tfq$, $tfq$What does HCP Terraform provide when a workspace uses remote execution?$tfq$, $tfq$A managed environment that runs Terraform plans and applies$tfq$, $tfq$A replacement cloud provider that owns all created resources$tfq$, $tfq$A local backend that stores state only on the user laptop$tfq$, $tfq$A compiler that converts HCL into provider source code$tfq$, NULL, NULL, 0, ARRAY[0]::INTEGER[], $tfq$Remote execution runs Terraform operations in HCP Terraform infrastructure while retaining workspace state, variables, history, and controls. Providers still create resources in their target platforms.$tfq$, $tfq$tf004-hcp$tfq$),
  ($tfq$q-tf004-96$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Medium$tfq$, $tfq$multiple$tfq$, $tfq$Which two HCP Terraform capabilities support reuse and governance across teams? Select two.$tfq$, $tfq$A private module and provider Registry$tfq$, $tfq$Policy checks integrated into run workflows$tfq$, $tfq$One shared administrator login for every workspace$tfq$, $tfq$Automatic removal of historical state versions$tfq$, $tfq$Credentials embedded in reusable module source code$tfq$, NULL, 0, ARRAY[0, 1]::INTEGER[], $tfq$The private Registry helps teams publish approved reusable modules and providers, while policy checks apply governance to runs. Shared accounts and embedded credentials undermine controlled collaboration.$tfq$, $tfq$tf004-hcp$tfq$),
  ($tfq$q-tf004-97$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Medium$tfq$, $tfq$single$tfq$, $tfq$An organization groups its networking workspaces into one HCP Terraform project. What can the project help administrators manage?$tfq$, $tfq$Organization and access boundaries for related workspaces$tfq$, $tfq$One combined state file shared by every networking workspace$tfq$, $tfq$A single provider version that overrides all lock files$tfq$, $tfq$Automatic conversion of workspaces into child modules$tfq$, NULL, NULL, 0, ARRAY[0]::INTEGER[], $tfq$Projects organize related workspaces and support project-scoped permissions and settings. Each workspace continues to have its own runs and state.$tfq$, $tfq$tf004-hcp$tfq$),
  ($tfq$q-tf004-98$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Medium$tfq$, $tfq$single$tfq$, $tfq$Which command authenticates the Terraform CLI to an HCP Terraform or Terraform Enterprise host?$tfq$, $tfq$terraform login$tfq$, $tfq$terraform cloud init$tfq$, $tfq$terraform auth provider$tfq$, $tfq$terraform workspace connect$tfq$, NULL, NULL, 0, ARRAY[0]::INTEGER[], $tfq$terraform login obtains and stores an API token for the selected HCP Terraform or Terraform Enterprise hostname. The token should be treated as sensitive.$tfq$, $tfq$tf004-hcp$tfq$),
  ($tfq$q-tf004-99$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Hard$tfq$, $tfq$single$tfq$, $tfq$A security scanning service must evaluate an HCP Terraform plan before apply and return a pass or fail result. Which integration is intended for this?$tfq$, $tfq$An HCP Terraform run task$tfq$, $tfq$A local backend workspace$tfq$, $tfq$A provider alias map$tfq$, $tfq$A dependency lock checksum$tfq$, NULL, NULL, 0, ARRAY[0]::INTEGER[], $tfq$Run tasks integrate external services at defined run stages so they can inspect run information and return a result. Enforcement settings determine whether a failed result blocks progress.$tfq$, $tfq$tf004-hcp$tfq$),
  ($tfq$q-tf004-100$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Hard$tfq$, $tfq$multiple$tfq$, $tfq$Which two statements describe HCP Terraform dynamic provider credentials? Select two.$tfq$, $tfq$They can issue short-lived cloud credentials for individual runs$tfq$, $tfq$They use a configured trust relationship with the target platform$tfq$, $tfq$They require permanent access keys committed to configuration$tfq$, $tfq$They combine all workspaces into one cloud administrator identity$tfq$, $tfq$They prevent providers from making any remote API requests$tfq$, NULL, 0, ARRAY[0, 1]::INTEGER[], $tfq$Dynamic credentials use a trust relationship, commonly based on workload identity, to obtain temporary credentials for a run. This reduces reliance on long-lived static keys.$tfq$, $tfq$tf004-hcp$tfq$);

DO $migration_guard$
BEGIN
  IF (SELECT COUNT(*) FROM terraform_004_question_seed) <> 100 THEN
    RAISE EXCEPTION 'Terraform question publication stopped: expected 100 seed questions.';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM public.exam_questions existing
    JOIN terraform_004_question_seed seed ON seed.id = existing.id
    WHERE existing.exam_code <> 'terraform-associate-004'
  ) THEN
    RAISE EXCEPTION 'Terraform question publication stopped: a question ID belongs to another exam.';
  END IF;
END
$migration_guard$;

INSERT INTO public.exam_questions (
  id, exam_code, difficulty, question_type, question_text,
  option_a, option_b, option_c, option_d, option_e, option_f,
  correct_answer, correct_answers, explanation
)
SELECT
  id, exam_code, difficulty, question_type, question_text,
  option_a, option_b, option_c, option_d, option_e, option_f,
  correct_answer, correct_answers, explanation
FROM terraform_004_question_seed
ON CONFLICT (id) DO UPDATE SET
  difficulty = EXCLUDED.difficulty,
  question_type = EXCLUDED.question_type,
  question_text = EXCLUDED.question_text,
  option_a = EXCLUDED.option_a,
  option_b = EXCLUDED.option_b,
  option_c = EXCLUDED.option_c,
  option_d = EXCLUDED.option_d,
  option_e = EXCLUDED.option_e,
  option_f = EXCLUDED.option_f,
  correct_answer = EXCLUDED.correct_answer,
  correct_answers = EXCLUDED.correct_answers,
  explanation = EXCLUDED.explanation
WHERE public.exam_questions.exam_code = EXCLUDED.exam_code;

DELETE FROM public.question_topics mappings
USING terraform_004_question_seed seed
WHERE mappings.question_id = seed.id;

INSERT INTO public.question_topics (question_id, topic_id)
SELECT id, topic_id
FROM terraform_004_question_seed
ON CONFLICT (question_id, topic_id) DO NOTHING;

DO $publication_check$
BEGIN
  IF (
    SELECT COUNT(*)
    FROM public.exam_questions questions
    JOIN terraform_004_question_seed seed ON seed.id = questions.id
    WHERE questions.exam_code = 'terraform-associate-004'
  ) <> 100 THEN
    RAISE EXCEPTION 'Terraform question publication failed verification: question count is not 100.';
  END IF;

  IF (
    SELECT COUNT(*)
    FROM public.question_topics mappings
    JOIN terraform_004_question_seed seed
      ON seed.id = mappings.question_id
     AND seed.topic_id = mappings.topic_id
  ) <> 100 THEN
    RAISE EXCEPTION 'Terraform question publication failed verification: topic mapping count is not 100.';
  END IF;
END
$publication_check$;

COMMIT;
