-- Publish the 50 locally reviewed Terraform Associate (004) questions.
-- Scope: Terraform questions q-tf004-1 through q-tf004-50 and their topic links only.
-- AWS questions, exam attempts, Follow Alongs, drafts and approvals are not changed.

BEGIN;

CREATE TEMP TABLE terraform_004_question_seed (
  id TEXT PRIMARY KEY,
  exam_code TEXT NOT NULL,
  difficulty TEXT,
  question_type TEXT NOT NULL,
  question_text TEXT NOT NULL,
  option_a TEXT NOT NULL,
  option_b TEXT NOT NULL,
  option_c TEXT NOT NULL,
  option_d TEXT NOT NULL,
  option_e TEXT,
  option_f TEXT,
  correct_answer INTEGER NOT NULL,
  correct_answers INTEGER[] NOT NULL,
  explanation TEXT,
  topic_id TEXT NOT NULL
) ON COMMIT DROP;

INSERT INTO terraform_004_question_seed (
  id, exam_code, difficulty, question_type, question_text,
  option_a, option_b, option_c, option_d, option_e, option_f,
  correct_answer, correct_answers, explanation, topic_id
) VALUES
  ($tfq$q-tf004-1$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Easy$tfq$, $tfq$single$tfq$, $tfq$A team currently creates development environments by following a shared checklist. What is the strongest reason to replace that process with Terraform configuration stored in version control?$tfq$, $tfq$It guarantees that cloud providers never change their service APIs$tfq$, $tfq$It makes infrastructure changes repeatable, reviewable, and auditable$tfq$, $tfq$It removes the need to authenticate to infrastructure providers$tfq$, $tfq$It prevents anyone from changing infrastructure outside Terraform$tfq$, NULL, NULL, 1, ARRAY[1]::INTEGER[], $tfq$Version-controlled Terraform configuration gives the team a repeatable definition of the intended infrastructure and a reviewable history of changes. It does not prevent drift, remove authentication, or control provider APIs.$tfq$, $tfq$tf004-iac$tfq$),
  ($tfq$q-tf004-2$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Medium$tfq$, $tfq$single$tfq$, $tfq$One Terraform configuration manages resources in AWS and an external monitoring service. How can Terraform use one workflow for both services?$tfq$, $tfq$It translates both services into the same native cloud template format$tfq$, $tfq$It stores each service object in a separate Terraform executable$tfq$, $tfq$It uses a provider plugin that implements each service API$tfq$, $tfq$It mirrors all service APIs into the Terraform state file$tfq$, NULL, NULL, 2, ARRAY[2]::INTEGER[], $tfq$Providers are plugins that let Terraform communicate with cloud, SaaS, and other service APIs. The workflow stays consistent while each provider implements the operations needed for its own service.$tfq$, $tfq$tf004-iac$tfq$),
  ($tfq$q-tf004-3$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Easy$tfq$, $tfq$single$tfq$, $tfq$A learner has cloned a valid Terraform configuration into a new empty working directory. Which command should they run before creating a plan?$tfq$, $tfq$terraform validate$tfq$, $tfq$terraform providers lock$tfq$, $tfq$terraform init$tfq$, $tfq$terraform refresh$tfq$, NULL, NULL, 2, ARRAY[2]::INTEGER[], $tfq$terraform init prepares the working directory, initializes the configured backend, and installs required providers and modules. Validation and planning normally follow initialization.$tfq$, $tfq$tf004-fundamentals$tfq$),
  ($tfq$q-tf004-4$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Medium$tfq$, $tfq$single$tfq$, $tfq$Why should a team commit the .terraform.lock.hcl dependency lock file to version control?$tfq$, $tfq$It stores the credentials used by every configured provider$tfq$, $tfq$It records selected provider versions and package checksums$tfq$, $tfq$It replaces all provider constraints in required_providers$tfq$, $tfq$It contains the latest remote objects recorded in state$tfq$, NULL, NULL, 1, ARRAY[1]::INTEGER[], $tfq$The dependency lock file records selected provider versions and checksums so later initialization can make consistent provider selections and verify downloaded packages. It does not store credentials or infrastructure state.$tfq$, $tfq$tf004-fundamentals$tfq$),
  ($tfq$q-tf004-5$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Easy$tfq$, $tfq$single$tfq$, $tfq$A change has been written and validated. Which command shows the proposed actions without changing the managed infrastructure?$tfq$, $tfq$terraform apply$tfq$, $tfq$terraform plan$tfq$, $tfq$terraform state show$tfq$, $tfq$terraform output$tfq$, NULL, NULL, 1, ARRAY[1]::INTEGER[], $tfq$terraform plan compares configuration, prior state, and refreshed remote object information to propose an execution plan. It does not apply the proposed infrastructure changes.$tfq$, $tfq$tf004-workflow$tfq$),
  ($tfq$q-tf004-6$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Medium$tfq$, $tfq$single$tfq$, $tfq$A team reviews a plan saved as tfplan. What is the main benefit of running terraform apply tfplan instead of terraform apply with no plan file?$tfq$, $tfq$Terraform applies the exact saved plan that the team reviewed$tfq$, $tfq$Terraform upgrades all providers before applying the changes$tfq$, $tfq$Terraform bypasses provider authentication for that operation$tfq$, $tfq$Terraform disables state refresh and locking for that operation$tfq$, NULL, NULL, 0, ARRAY[0]::INTEGER[], $tfq$Supplying a saved plan tells Terraform to apply that reviewed plan rather than generating a new speculative plan. Provider authentication and normal safety behavior are still required.$tfq$, $tfq$tf004-workflow$tfq$),
  ($tfq$q-tf004-7$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Easy$tfq$, $tfq$single$tfq$, $tfq$A network already exists and Terraform only needs to read its attributes for use by another resource. Which block type is most appropriate?$tfq$, $tfq$A resource block$tfq$, $tfq$A moved block$tfq$, $tfq$A data block$tfq$, $tfq$An output block$tfq$, NULL, NULL, 2, ARRAY[2]::INTEGER[], $tfq$A data block reads information from an existing object without declaring that object as managed by the current configuration. A resource block is used when Terraform should manage the object lifecycle.$tfq$, $tfq$tf004-configuration$tfq$),
  ($tfq$q-tf004-8$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Medium$tfq$, $tfq$single$tfq$, $tfq$When should an author normally add an explicit depends_on relationship?$tfq$, $tfq$Whenever two resources use the same provider configuration$tfq$, $tfq$When a required dependency is not visible in value references$tfq$, $tfq$Whenever a resource has more than one configuration argument$tfq$, $tfq$When a variable value is supplied from a tfvars file$tfq$, NULL, NULL, 1, ARRAY[1]::INTEGER[], $tfq$Terraform infers dependencies from references in expressions. depends_on is appropriate for a real behavioral dependency that Terraform cannot infer from those references.$tfq$, $tfq$tf004-configuration$tfq$),
  ($tfq$q-tf004-9$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Easy$tfq$, $tfq$single$tfq$, $tfq$How does a root module normally pass an environment name into a child module?$tfq$, $tfq$By assigning a value to a declared child-module input$tfq$, $tfq$By writing the value directly into the child state file$tfq$, $tfq$By adding the value to the provider dependency lock file$tfq$, $tfq$By exporting the value from a saved execution plan$tfq$, NULL, NULL, 0, ARRAY[0]::INTEGER[], $tfq$The child module declares an input variable and the calling module assigns its value in the module block. Module inputs form the supported interface between the caller and child.$tfq$, $tfq$tf004-modules$tfq$),
  ($tfq$q-tf004-10$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Medium$tfq$, $tfq$single$tfq$, $tfq$A team wants a publicly discoverable module with published versions and documentation. Which source is designed for this use?$tfq$, $tfq$A local Terraform state file$tfq$, $tfq$A saved Terraform plan file$tfq$, $tfq$The Terraform dependency lock file$tfq$, $tfq$The public Terraform Registry$tfq$, NULL, NULL, 3, ARRAY[3]::INTEGER[], $tfq$The public Terraform Registry provides discoverable and versioned modules with documentation. Local state, plan files, and provider lock files are not module distribution services.$tfq$, $tfq$tf004-modules$tfq$),
  ($tfq$q-tf004-11$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Easy$tfq$, $tfq$single$tfq$, $tfq$What essential relationship does Terraform state record?$tfq$, $tfq$Provider binaries mapped to their download locations$tfq$, $tfq$Resource addresses mapped to real infrastructure objects$tfq$, $tfq$Variable names mapped to environment variable files$tfq$, $tfq$Module sources mapped to version-control branches$tfq$, NULL, NULL, 1, ARRAY[1]::INTEGER[], $tfq$State maps Terraform resource instances and their addresses to real remote objects, while also retaining metadata needed to plan and manage those objects.$tfq$, $tfq$tf004-state$tfq$),
  ($tfq$q-tf004-12$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Medium$tfq$, $tfq$single$tfq$, $tfq$Two engineers start operations against the same remote state at nearly the same time. Which backend capability reduces the risk of both operations writing state concurrently?$tfq$, $tfq$State locking$tfq$, $tfq$Provider aliasing$tfq$, $tfq$Output sensitivity$tfq$, $tfq$Module versioning$tfq$, NULL, NULL, 0, ARRAY[0]::INTEGER[], $tfq$State locking prevents supported operations from acquiring the same state for modification at the same time. The selected backend must support the relevant locking mechanism.$tfq$, $tfq$tf004-state$tfq$),
  ($tfq$q-tf004-13$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Easy$tfq$, $tfq$single$tfq$, $tfq$What is the immediate result of successfully importing an existing object to a Terraform resource address?$tfq$, $tfq$Terraform recreates the object using its default arguments$tfq$, $tfq$Terraform associates the existing object with the chosen address$tfq$, $tfq$Terraform generates a complete production-ready module automatically$tfq$, $tfq$Terraform moves the object into the account used by the provider$tfq$, NULL, NULL, 1, ARRAY[1]::INTEGER[], $tfq$Import binds an existing remote object to a selected Terraform resource address. The practitioner must still provide and review configuration that represents the desired managed object.$tfq$, $tfq$tf004-maintenance$tfq$),
  ($tfq$q-tf004-14$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Medium$tfq$, $tfq$single$tfq$, $tfq$A Terraform command fails without enough diagnostic detail. Which environment variable controls Terraform core log verbosity?$tfq$, $tfq$TF_INPUT$tfq$, $tfq$TF_DATA_DIR$tfq$, $tfq$TF_LOG$tfq$, $tfq$TF_VAR_name$tfq$, NULL, NULL, 2, ARRAY[2]::INTEGER[], $tfq$TF_LOG sets the Terraform core logging level, such as DEBUG or TRACE. Logs can contain sensitive information, so they should be enabled temporarily and handled carefully.$tfq$, $tfq$tf004-maintenance$tfq$),
  ($tfq$q-tf004-15$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Easy$tfq$, $tfq$single$tfq$, $tfq$Which collection of information is normally associated with an HCP Terraform workspace?$tfq$, $tfq$Provider source code, plugin releases, and Registry ownership$tfq$, $tfq$Configuration connection, variables, state, and run history$tfq$, $tfq$Cloud root credentials, billing data, and support tickets$tfq$, $tfq$Only a local plan file and the current CLI process$tfq$, NULL, NULL, 1, ARRAY[1]::INTEGER[], $tfq$An HCP Terraform workspace organizes the configuration source or workflow, variables, state, and run history used to manage a particular collection of infrastructure.$tfq$, $tfq$tf004-hcp$tfq$),
  ($tfq$q-tf004-16$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Medium$tfq$, $tfq$single$tfq$, $tfq$An organization must evaluate infrastructure changes against governance rules before an apply. Which HCP Terraform capability addresses this requirement?$tfq$, $tfq$Provider aliasing$tfq$, $tfq$Policy enforcement$tfq$, $tfq$Local state storage$tfq$, $tfq$Configuration formatting$tfq$, NULL, NULL, 1, ARRAY[1]::INTEGER[], $tfq$HCP Terraform policy enforcement evaluates runs against organizational policies at defined enforcement levels. Provider aliases, local state, and formatting do not provide governance decisions.$tfq$, $tfq$tf004-hcp$tfq$),
  ($tfq$q-tf004-17$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Medium$tfq$, $tfq$single$tfq$, $tfq$A resource must use the alternate AWS provider configuration declared with alias = "west". Which resource meta-argument selects it?$tfq$, $tfq$providers = aws.west$tfq$, $tfq$region = aws.west$tfq$, $tfq$provider = aws.west$tfq$, $tfq$source = aws.west$tfq$, NULL, NULL, 2, ARRAY[2]::INTEGER[], $tfq$A resource selects an alternate provider configuration with the provider meta-argument and the local provider reference, such as provider = aws.west.$tfq$, $tfq$tf004-fundamentals$tfq$),
  ($tfq$q-tf004-18$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Medium$tfq$, $tfq$single$tfq$, $tfq$What does sensitive = true on a Terraform variable guarantee?$tfq$, $tfq$The value is encrypted automatically in every possible backend$tfq$, $tfq$The value is omitted permanently from all state snapshots$tfq$, $tfq$The value is redacted from normal Terraform CLI presentation$tfq$, $tfq$The provider is prevented from receiving the variable value$tfq$, NULL, NULL, 2, ARRAY[2]::INTEGER[], $tfq$The sensitive flag redacts the value from normal CLI and UI presentation. It does not guarantee encryption or omission from state, so state and access to it must still be protected.$tfq$, $tfq$tf004-configuration$tfq$),
  ($tfq$q-tf004-19$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Medium$tfq$, $tfq$single$tfq$, $tfq$A resource replacement must minimize interruption when the remote API permits both objects to exist briefly. Which lifecycle setting is intended for this behavior?$tfq$, $tfq$prevent_destroy$tfq$, $tfq$ignore_changes$tfq$, $tfq$create_before_destroy$tfq$, $tfq$replace_triggered_by$tfq$, NULL, NULL, 2, ARRAY[2]::INTEGER[], $tfq$create_before_destroy requests creation of the replacement before deletion of the prior object. Provider and naming constraints can still prevent both objects from existing simultaneously.$tfq$, $tfq$tf004-configuration$tfq$),
  ($tfq$q-tf004-20$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Hard$tfq$, $tfq$multiple$tfq$, $tfq$Which two features can stop an operation when a custom condition is not satisfied? Select two.$tfq$, $tfq$A variable validation block$tfq$, $tfq$A resource precondition block$tfq$, $tfq$A dependency lock file checksum$tfq$, $tfq$A local backend path setting$tfq$, $tfq$A provider configuration alias$tfq$, NULL, 0, ARRAY[0, 1]::INTEGER[], $tfq$Variable validation rejects unsuitable input values, and a precondition prevents an operation when its required assumption is false. Lock checksums, backend paths, and aliases serve different purposes.$tfq$, $tfq$tf004-configuration$tfq$),
  ($tfq$q-tf004-21$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Medium$tfq$, $tfq$single$tfq$, $tfq$Why is for_each often safer than count for instances identified by stable names?$tfq$, $tfq$It identifies instances by keys instead of changing list positions$tfq$, $tfq$It prevents every instance from ever being replaced by Terraform$tfq$, $tfq$It automatically stores each instance in a separate state file$tfq$, $tfq$It lets one resource use providers from unrelated source addresses$tfq$, NULL, NULL, 0, ARRAY[0]::INTEGER[], $tfq$for_each uses map keys or set members in instance addresses. Stable keys can avoid the address shifting that may occur when count indexes an ordered list whose members change.$tfq$, $tfq$tf004-configuration$tfq$),
  ($tfq$q-tf004-22$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Medium$tfq$, $tfq$single$tfq$, $tfq$Where is a version constraint specified for a module sourced from a Terraform Registry?$tfq$, $tfq$In the backend block$tfq$, $tfq$In the module block$tfq$, $tfq$In the provider block$tfq$, $tfq$In the output block$tfq$, NULL, NULL, 1, ARRAY[1]::INTEGER[], $tfq$A Registry module call can use the version argument inside its module block. The version argument is not supported for every module source type.$tfq$, $tfq$tf004-modules$tfq$),
  ($tfq$q-tf004-23$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Medium$tfq$, $tfq$single$tfq$, $tfq$A team changes from the local backend to a configured remote backend and wants Terraform to copy the existing state. Which command is appropriate?$tfq$, $tfq$terraform state push -force$tfq$, $tfq$terraform init -migrate-state$tfq$, $tfq$terraform plan -refresh-only$tfq$, $tfq$terraform apply -replace-state$tfq$, NULL, NULL, 1, ARRAY[1]::INTEGER[], $tfq$terraform init -migrate-state reinitializes the working directory for the changed backend configuration and prompts to migrate existing state to the new backend.$tfq$, $tfq$tf004-state$tfq$),
  ($tfq$q-tf004-24$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Medium$tfq$, $tfq$single$tfq$, $tfq$An administrator changed a tag directly in the cloud console. The team wants to review updating state to match that remote change without modifying the remote object. Which plan mode should they use?$tfq$, $tfq$A destroy plan$tfq$, $tfq$A targeted plan$tfq$, $tfq$A refresh-only plan$tfq$, $tfq$A saved replacement plan$tfq$, NULL, NULL, 2, ARRAY[2]::INTEGER[], $tfq$Refresh-only mode proposes updates to Terraform state and root outputs so they match changes already made to remote objects, without proposing corrective changes to those objects.$tfq$, $tfq$tf004-state$tfq$),
  ($tfq$q-tf004-25$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Hard$tfq$, $tfq$single$tfq$, $tfq$A resource block is moved into a child module, but the real object must remain unchanged. Which configuration construct records the address change?$tfq$, $tfq$A check block$tfq$, $tfq$A moved block$tfq$, $tfq$A dynamic block$tfq$, $tfq$A terraform_data block$tfq$, NULL, NULL, 1, ARRAY[1]::INTEGER[], $tfq$A moved block maps the old resource address to the new address. Terraform can then preserve the existing object while recording the refactor in configuration.$tfq$, $tfq$tf004-state$tfq$),
  ($tfq$q-tf004-26$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Medium$tfq$, $tfq$multiple$tfq$, $tfq$Which two statements describe a safe import workflow? Select two.$tfq$, $tfq$Choose the destination resource address deliberately$tfq$, $tfq$Assume import creates a complete production configuration$tfq$, $tfq$Create and review configuration for the imported object$tfq$, $tfq$Expect import to move the object between cloud accounts$tfq$, $tfq$Delete the object remotely before running the import$tfq$, NULL, 0, ARRAY[0, 2]::INTEGER[], $tfq$The practitioner selects the Terraform address and supplies configuration that should manage the existing object. Import does not relocate or recreate the object, and generated configuration still requires review.$tfq$, $tfq$tf004-maintenance$tfq$),
  ($tfq$q-tf004-27$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Easy$tfq$, $tfq$multiple$tfq$, $tfq$Which two commands inspect Terraform state without changing resource addresses or removing records? Select two.$tfq$, $tfq$terraform state list$tfq$, $tfq$terraform state show$tfq$, $tfq$terraform state mv$tfq$, $tfq$terraform state rm$tfq$, $tfq$terraform state push$tfq$, NULL, 0, ARRAY[0, 1]::INTEGER[], $tfq$terraform state list displays tracked addresses and terraform state show displays attributes for a selected address. The mv, rm, and push operations can change state data.$tfq$, $tfq$tf004-maintenance$tfq$),
  ($tfq$q-tf004-28$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Hard$tfq$, $tfq$single$tfq$, $tfq$What distinguishes an ephemeral value from a value that is only marked sensitive?$tfq$, $tfq$An ephemeral value is always stored in a separate encrypted state file$tfq$, $tfq$An ephemeral value is omitted from Terraform plan and state artifacts$tfq$, $tfq$An ephemeral value can be referenced from every configuration context$tfq$, $tfq$An ephemeral value removes the need to protect provider log output$tfq$, NULL, NULL, 1, ARRAY[1]::INTEGER[], $tfq$Terraform omits ephemeral values from plan and state artifacts and restricts where they can be used. A sensitive value is normally redacted from display but can still be persisted in state.$tfq$, $tfq$tf004-configuration$tfq$),
  ($tfq$q-tf004-29$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Medium$tfq$, $tfq$single$tfq$, $tfq$What can a VCS-connected HCP Terraform workspace do when a relevant approved commit is pushed?$tfq$, $tfq$Queue a run based on the workspace VCS configuration$tfq$, $tfq$Apply changes while permanently skipping the plan stage$tfq$, $tfq$Overwrite the repository with the current remote state$tfq$, $tfq$Run every workspace in the organization unconditionally$tfq$, NULL, NULL, 0, ARRAY[0]::INTEGER[], $tfq$A VCS-connected workspace can detect relevant repository changes and queue runs according to its configuration. The normal run and approval controls still apply.$tfq$, $tfq$tf004-hcp$tfq$),
  ($tfq$q-tf004-30$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Hard$tfq$, $tfq$multiple$tfq$, $tfq$Which two HCP Terraform features directly support controlled team workflows? Select two.$tfq$, $tfq$Team-based workspace permissions$tfq$, $tfq$Removal of all historical state versions$tfq$, $tfq$Policy enforcement during run workflows$tfq$, $tfq$Credentials committed inside configuration files$tfq$, $tfq$Automatic bypass of mandatory run approvals$tfq$, NULL, 0, ARRAY[0, 2]::INTEGER[], $tfq$Team permissions control access to workspaces and actions, while policy enforcement evaluates proposed changes against organizational rules. The other choices weaken rather than support controlled collaboration.$tfq$, $tfq$tf004-hcp$tfq$),
  ($tfq$q-tf004-31$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Medium$tfq$, $tfq$single$tfq$, $tfq$A cloud object was changed manually after the last Terraform apply. What best describes Terraform's desired-state approach during the next plan?$tfq$, $tfq$Terraform ignores the object because it already exists remotely$tfq$, $tfq$Terraform compares configuration, state, and refreshed remote data$tfq$, $tfq$Terraform immediately changes the object before showing a plan$tfq$, $tfq$Terraform rewrites configuration to match every manual change$tfq$, NULL, NULL, 1, ARRAY[1]::INTEGER[], $tfq$Terraform creates a plan by reconciling the desired configuration with prior state and refreshed information about remote objects. It then proposes actions; it does not silently rewrite configuration or apply during planning.$tfq$, $tfq$tf004-iac$tfq$),
  ($tfq$q-tf004-32$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Medium$tfq$, $tfq$multiple$tfq$, $tfq$Which two entries belong in a required_providers declaration for a provider requirement? Select two.$tfq$, $tfq$The provider source address$tfq$, $tfq$The provider authentication token$tfq$, $tfq$An acceptable version constraint$tfq$, $tfq$The current remote resource IDs$tfq$, $tfq$The backend state-lock identifier$tfq$, NULL, 0, ARRAY[0, 2]::INTEGER[], $tfq$required_providers declares where a provider comes from and which versions are acceptable. Authentication belongs in provider configuration or secure external mechanisms, not in provider requirements.$tfq$, $tfq$tf004-fundamentals$tfq$),
  ($tfq$q-tf004-33$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Hard$tfq$, $tfq$single$tfq$, $tfq$A child module expects an alternate AWS configuration named aws.replica. How should the caller pass its own aws.west configuration to that child?$tfq$, $tfq$Set provider = aws.replica inside every child resource from the caller$tfq$, $tfq$Set providers = { aws.replica = aws.west } in the module block$tfq$, $tfq$Set aliases = { aws.west = aws.replica } in required_providers$tfq$, $tfq$Set source = aws.west in the child module output block$tfq$, NULL, NULL, 1, ARRAY[1]::INTEGER[], $tfq$The module call uses its providers map to associate the child module provider name with a provider configuration in the caller. The child must declare any configuration aliases it expects.$tfq$, $tfq$tf004-fundamentals$tfq$),
  ($tfq$q-tf004-34$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Medium$tfq$, $tfq$single$tfq$, $tfq$The configuration permits a newer provider version, but the dependency lock file retains an older selection. Which command asks Terraform to reconsider allowed provider selections?$tfq$, $tfq$terraform init -upgrade$tfq$, $tfq$terraform validate -upgrade$tfq$, $tfq$terraform plan -replace$tfq$, $tfq$terraform providers mirror$tfq$, NULL, NULL, 0, ARRAY[0]::INTEGER[], $tfq$terraform init -upgrade ignores the existing provider selections when choosing among versions allowed by the configured constraints, then updates the lock file as needed.$tfq$, $tfq$tf004-workflow$tfq$),
  ($tfq$q-tf004-35$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Medium$tfq$, $tfq$multiple$tfq$, $tfq$Which two statements correctly distinguish terraform fmt and terraform validate? Select two.$tfq$, $tfq$terraform fmt rewrites configuration into canonical style$tfq$, $tfq$terraform fmt confirms provider credentials can create resources$tfq$, $tfq$terraform validate checks configuration syntax and internal consistency$tfq$, $tfq$terraform validate applies safe formatting changes automatically$tfq$, $tfq$terraform validate confirms that a saved plan is still current$tfq$, NULL, 0, ARRAY[0, 2]::INTEGER[], $tfq$terraform fmt applies Terraform language style conventions. terraform validate checks whether a configuration is syntactically valid and internally consistent, but does not validate remote credentials or apply formatting.$tfq$, $tfq$tf004-workflow$tfq$),
  ($tfq$q-tf004-36$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Hard$tfq$, $tfq$single$tfq$, $tfq$A saved plan was created, but another successful apply changed the same workspace state before the saved plan was used. What should the team expect?$tfq$, $tfq$Terraform should reject the stale plan rather than apply it blindly$tfq$, $tfq$Terraform should merge both plans without recalculating dependencies$tfq$, $tfq$Terraform should delete the newer state and restore the saved state$tfq$, $tfq$Terraform should apply only resource creates from the older plan$tfq$, NULL, NULL, 0, ARRAY[0]::INTEGER[], $tfq$A saved plan is tied to the state and configuration context from which it was created. If the state has changed, Terraform detects that the plan is stale and requires a new plan.$tfq$, $tfq$tf004-workflow$tfq$),
  ($tfq$q-tf004-37$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Medium$tfq$, $tfq$single$tfq$, $tfq$A data source reads an image ID that is then assigned to a managed instance resource. What dependency behavior results from that reference?$tfq$, $tfq$Terraform infers that the data source must be read before planning the instance value$tfq$, $tfq$Terraform creates and later destroys the image represented by the data source$tfq$, $tfq$Terraform requires depends_on because data sources never create dependencies$tfq$, $tfq$Terraform copies the complete data source object into the instance state address$tfq$, NULL, NULL, 0, ARRAY[0]::INTEGER[], $tfq$The reference creates an implicit dependency in Terraform's graph. The data source reads information; it does not cause the referenced remote object to become managed by the resource lifecycle.$tfq$, $tfq$tf004-configuration$tfq$),
  ($tfq$q-tf004-38$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Hard$tfq$, $tfq$single$tfq$, $tfq$A variable has a default, a value in terraform.tfvars, and a value supplied with -var on the command line. Which value is used for that CLI-driven run?$tfq$, $tfq$The declared default because configuration has highest precedence$tfq$, $tfq$The terraform.tfvars value because it is loaded automatically$tfq$, $tfq$The command-line -var value because it has higher precedence$tfq$, $tfq$Terraform stops because the variable has more than one value source$tfq$, NULL, NULL, 2, ARRAY[2]::INTEGER[], $tfq$For the Terraform CLI variable-loading order, command-line -var and -var-file assignments take precedence over automatically loaded tfvars values and declared defaults.$tfq$, $tfq$tf004-configuration$tfq$),
  ($tfq$q-tf004-39$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Medium$tfq$, $tfq$single$tfq$, $tfq$A module needs a named collection whose values each contain a CIDR string and a Boolean public flag. Which type constraint best represents this input?$tfq$, $tfq$list(string)$tfq$, $tfq$map(object({ cidr = string, public = bool }))$tfq$, $tfq$tuple([string, bool])$tfq$, $tfq$set(map(string))$tfq$, NULL, NULL, 1, ARRAY[1]::INTEGER[], $tfq$A map provides stable names as keys, while each object enforces the cidr string and public Boolean attributes. The other types do not model a named collection of consistently shaped records.$tfq$, $tfq$tf004-configuration$tfq$),
  ($tfq$q-tf004-40$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Hard$tfq$, $tfq$single$tfq$, $tfq$Which expression returns only enabled service names from var.services, where each map value has an enabled Boolean attribute?$tfq$, $tfq$[for name, service in var.services : name if service.enabled]$tfq$, $tfq$[for name in var.services : service.enabled => name]$tfq$, $tfq$for_each(var.services, service.enabled, name)$tfq$, $tfq$filter(var.services[*].name, enabled = true)$tfq$, NULL, NULL, 0, ARRAY[0]::INTEGER[], $tfq$A for expression can transform each map element to its name and use an if clause to filter out values whose enabled attribute is false.$tfq$, $tfq$tf004-configuration$tfq$),
  ($tfq$q-tf004-41$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Hard$tfq$, $tfq$single$tfq$, $tfq$A resource must be created only when an input assumption is valid. Which custom condition is the closest fit?$tfq$, $tfq$A postcondition that is evaluated only after every future run$tfq$, $tfq$A precondition attached to the resource lifecycle$tfq$, $tfq$A check block that automatically changes the invalid input$tfq$, $tfq$A variable output that replaces the resource dependency$tfq$, NULL, NULL, 1, ARRAY[1]::INTEGER[], $tfq$A resource precondition checks an assumption before Terraform performs the associated resource operation and can stop the operation with a useful error message.$tfq$, $tfq$tf004-configuration$tfq$),
  ($tfq$q-tf004-42$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Hard$tfq$, $tfq$multiple$tfq$, $tfq$Which two statements about supported write-only resource arguments are correct? Select two.$tfq$, $tfq$Their configured values are not persisted in plan or state files$tfq$, $tfq$Every resource argument becomes write-only when marked sensitive$tfq$, $tfq$Provider support determines whether an argument is write-only$tfq$, $tfq$They can be read later with terraform state show$tfq$, $tfq$They remove the need to secure provider and Terraform logs$tfq$, NULL, 0, ARRAY[0, 2]::INTEGER[], $tfq$A provider schema defines supported write-only arguments, and Terraform does not persist their values in plan or state artifacts. They are different from sensitive values and do not make logging automatically safe.$tfq$, $tfq$tf004-configuration$tfq$),
  ($tfq$q-tf004-43$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Medium$tfq$, $tfq$single$tfq$, $tfq$A root module needs the subnet ID created inside a child module. What should form the child module interface for this value?$tfq$, $tfq$A child output referenced as module.network.subnet_id$tfq$, $tfq$A direct reference to the child resource local address$tfq$, $tfq$A backend block copied from the child into the caller$tfq$, $tfq$A provider lock entry exported by the child module$tfq$, NULL, NULL, 0, ARRAY[0]::INTEGER[], $tfq$The child module declares an output and the caller reads it through the module object. A caller cannot directly address a resource inside the child module as if it were in the same scope.$tfq$, $tfq$tf004-modules$tfq$),
  ($tfq$q-tf004-44$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Hard$tfq$, $tfq$single$tfq$, $tfq$A module block uses a local path source and also sets version = "~> 2.0". What is the problem?$tfq$, $tfq$Local modules cannot declare input variables or output values$tfq$, $tfq$The version argument applies to Registry module sources, not local paths$tfq$, $tfq$Local modules must be downloaded with terraform providers mirror$tfq$, $tfq$The version constraint must be moved into the provider configuration$tfq$, NULL, NULL, 1, ARRAY[1]::INTEGER[], $tfq$The module version argument is supported for Registry module sources. A local-path module uses the files at that path and is not selected through a Registry version constraint.$tfq$, $tfq$tf004-modules$tfq$),
  ($tfq$q-tf004-45$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Medium$tfq$, $tfq$multiple$tfq$, $tfq$Which two characteristics describe the default local backend? Select two.$tfq$, $tfq$It stores state on the local filesystem by default$tfq$, $tfq$It automatically provides shared remote collaboration$tfq$, $tfq$It performs Terraform operations on the local machine$tfq$, $tfq$It automatically encrypts state with HCP Terraform keys$tfq$, $tfq$It requires a cloud object-storage bucket for every workspace$tfq$, NULL, 0, ARRAY[0, 2]::INTEGER[], $tfq$The local backend stores state locally and executes operations locally. It does not by itself provide remote shared state, hosted encryption, or an object-storage requirement.$tfq$, $tfq$tf004-state$tfq$),
  ($tfq$q-tf004-46$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Hard$tfq$, $tfq$single$tfq$, $tfq$Why can a backend block not use normal input-variable references for all of its settings?$tfq$, $tfq$Backend initialization occurs before normal expression evaluation is available$tfq$, $tfq$Backends can only store state for configurations without any variables$tfq$, $tfq$Backend settings are copied from the provider dependency lock file$tfq$, $tfq$Terraform evaluates backend settings only after resources are applied$tfq$, NULL, NULL, 0, ARRAY[0]::INTEGER[], $tfq$Terraform must initialize the backend before it can perform the normal evaluation and planning workflow. Backend configuration therefore has restrictions and can also receive partial settings during initialization.$tfq$, $tfq$tf004-state$tfq$),
  ($tfq$q-tf004-47$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Hard$tfq$, $tfq$single$tfq$, $tfq$A team wants Terraform to stop managing an object without destroying the remote object, and wants the decision recorded in configuration. Which construct should they consider?$tfq$, $tfq$A removed block$tfq$, $tfq$A dynamic block$tfq$, $tfq$A check block$tfq$, $tfq$A terraform block$tfq$, NULL, NULL, 0, ARRAY[0]::INTEGER[], $tfq$A removed block can record that a resource is intentionally removed from Terraform management and, when configured not to destroy, preserve the remote object while removing it from state.$tfq$, $tfq$tf004-state$tfq$),
  ($tfq$q-tf004-48$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Hard$tfq$, $tfq$single$tfq$, $tfq$What advantage does an import block provide compared with relying only on a one-time terraform import CLI command?$tfq$, $tfq$It records the import request in reviewable configuration$tfq$, $tfq$It guarantees that generated configuration needs no review$tfq$, $tfq$It moves the imported object into the provider account$tfq$, $tfq$It prevents Terraform from refreshing the imported object$tfq$, NULL, NULL, 0, ARRAY[0]::INTEGER[], $tfq$An import block makes the intended import part of configuration, so it can be planned and reviewed with the rest of the change. Any generated or authored resource configuration still requires careful review.$tfq$, $tfq$tf004-maintenance$tfq$),
  ($tfq$q-tf004-49$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Medium$tfq$, $tfq$multiple$tfq$, $tfq$Which two statements correctly describe HCP Terraform projects and variable sets? Select two.$tfq$, $tfq$Projects can group related workspaces for organization and access control$tfq$, $tfq$Variable sets can provide reusable variables to selected workspaces or projects$tfq$, $tfq$Projects replace provider plugins with built-in cloud API clients$tfq$, $tfq$Variable sets are committed automatically to every linked repository$tfq$, $tfq$Projects force all workspaces to share one Terraform state file$tfq$, NULL, 0, ARRAY[0, 1]::INTEGER[], $tfq$Projects organize related workspaces and can support project-level permissions. Variable sets let teams reuse common variable definitions across selected scopes without forcing workspaces to share state.$tfq$, $tfq$tf004-hcp$tfq$),
  ($tfq$q-tf004-50$tfq$, $tfq$terraform-associate-004$tfq$, $tfq$Hard$tfq$, $tfq$multiple$tfq$, $tfq$Which two HCP Terraform features reduce manual coordination between connected workspaces and cloud credentials? Select two.$tfq$, $tfq$Run triggers that queue downstream workspace runs$tfq$, $tfq$Dynamic provider credentials issued for a run$tfq$, $tfq$A shared plaintext credentials file committed to VCS$tfq$, $tfq$One state file reused by every project workspace$tfq$, $tfq$Automatic approval of every policy failure$tfq$, NULL, 0, ARRAY[0, 1]::INTEGER[], $tfq$Run triggers coordinate dependent workspace runs, while dynamic provider credentials can issue short-lived credentials for an HCP Terraform run. The other options weaken isolation or governance.$tfq$, $tfq$tf004-hcp$tfq$);

DO $migration_guard$
BEGIN
  IF (SELECT COUNT(*) FROM terraform_004_question_seed) <> 50 THEN
    RAISE EXCEPTION 'Terraform question publication stopped: expected 50 seed questions.';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM public.exam_questions existing
    JOIN terraform_004_question_seed seed ON seed.id = existing.id
    WHERE existing.exam_code <> 'terraform-associate-004'
  ) THEN
    RAISE EXCEPTION 'Terraform question publication stopped: a question ID belongs to another exam.';
  END IF;
END
$migration_guard$;

INSERT INTO public.exam_questions (
  id, exam_code, difficulty, question_type, question_text,
  option_a, option_b, option_c, option_d, option_e, option_f,
  correct_answer, correct_answers, explanation
)
SELECT
  id, exam_code, difficulty, question_type, question_text,
  option_a, option_b, option_c, option_d, option_e, option_f,
  correct_answer, correct_answers, explanation
FROM terraform_004_question_seed
ON CONFLICT (id) DO UPDATE SET
  difficulty = EXCLUDED.difficulty,
  question_type = EXCLUDED.question_type,
  question_text = EXCLUDED.question_text,
  option_a = EXCLUDED.option_a,
  option_b = EXCLUDED.option_b,
  option_c = EXCLUDED.option_c,
  option_d = EXCLUDED.option_d,
  option_e = EXCLUDED.option_e,
  option_f = EXCLUDED.option_f,
  correct_answer = EXCLUDED.correct_answer,
  correct_answers = EXCLUDED.correct_answers,
  explanation = EXCLUDED.explanation
WHERE public.exam_questions.exam_code = EXCLUDED.exam_code;

DELETE FROM public.question_topics mappings
USING terraform_004_question_seed seed
WHERE mappings.question_id = seed.id;

INSERT INTO public.question_topics (question_id, topic_id)
SELECT id, topic_id
FROM terraform_004_question_seed
ON CONFLICT (question_id, topic_id) DO NOTHING;

DO $publication_check$
BEGIN
  IF (
    SELECT COUNT(*)
    FROM public.exam_questions questions
    JOIN terraform_004_question_seed seed ON seed.id = questions.id
    WHERE questions.exam_code = 'terraform-associate-004'
  ) <> 50 THEN
    RAISE EXCEPTION 'Terraform question publication failed verification: question count is not 50.';
  END IF;

  IF (
    SELECT COUNT(*)
    FROM public.question_topics mappings
    JOIN terraform_004_question_seed seed
      ON seed.id = mappings.question_id
     AND seed.topic_id = mappings.topic_id
  ) <> 50 THEN
    RAISE EXCEPTION 'Terraform question publication failed verification: topic mapping count is not 50.';
  END IF;
END
$publication_check$;

COMMIT;
